(() => {
 'use strict';
 const rows={
 externalActivities:['Workshop and route interests','Interés en talleres y rutas','Interesse em oficinas e roteiros'],
 externalInterestHint:['Save your interests here, then complete each activity’s Google Form to register with its facilitator. Interest in NODAL does not confirm that registration or attendance.','Guarda aquí tus actividades de interés y completa el Google Form de cada una para inscribirte con su facilitador. El interés en NODAL no confirma esa inscripción ni la asistencia.','Salve seus interesses aqui e preencha o Google Forms de cada atividade para se inscrever com o facilitador. O interesse na NODAL não confirma essa inscrição nem a presença.'],
 partyHint:['The closing party has separate registration. Check its details with the festival organisers.','La fiesta de cierre tiene inscripción independiente. Consulta los detalles con la organización del festival.','A festa de encerramento tem inscrição independente. Consulte os detalhes com a organização do festival.'],
 accessibilityHint:['Choose any support you need, or explicitly select no additional support.','Selecciona el apoyo que necesitas o indica que no necesitas apoyo adicional.','Selecione o apoio de que precisa ou indique que não precisa de apoio adicional.'],
 accessibilityRequired:['Choose an accessibility answer, including no additional support if appropriate.','Elige una respuesta de accesibilidad, incluyendo no necesito apoyo adicional cuando corresponda.','Escolha uma resposta sobre acessibilidade, incluindo não preciso de apoio adicional quando for o caso.'],
 apply:['Apply','Postular','Candidatar-se'],
 summaryTitle:['Registration overview','Resumen de inscripciones','Resumo das inscrições'],
 refreshSummary:['Refresh totals','Actualizar totales','Atualizar totais'],
 totalRegistrations:['Event registrations','Inscripciones al evento','Inscrições no evento'],
 publicOfficials:['Public officials','Funcionarios públicos','Gestores públicos'],
 byDay:['By day','Por día','Por dia'],byActivity:['By activity','Por actividad','Por atividade'],profiles:['Participant profiles','Perfiles de participantes','Perfis dos participantes'],
 participantCount:['People','Personas','Pessoas'],registered:['Registered / applied','Inscripciones / postulaciones','Inscrições / candidaturas'],attended:['Checked in','Asistencia','Presença'],day:['Day','Día','Dia'],activity:['Activity','Actividad','Atividade'],unspecified:['Not provided','No informado','Não informado'],
 activities:['Conference registrations','Inscripciones a conferencias','Inscrições nas conferências'],
 accountChanged:['Your signed-in account changed. Your draft is still here. Reload to continue with the current account.','Tu cuenta ha cambiado. Tu borrador sigue aquí. Recarga para continuar con la cuenta actual.','Sua conta mudou. Seu rascunho continua aqui. Recarregue para continuar com a conta atual.'],
 reloadAccount:['Reload for current account','Recargar para la cuenta actual','Recarregar para a conta atual'],
 reloadSaved:['Reload saved registration','Recargar inscripción guardada','Recarregar inscrição salva'],
 savedRefreshFailed:['Saved, but the latest list could not be loaded. Your changes are safe.','Guardado, pero no se pudo cargar la lista actualizada. Tus cambios están guardados.','Salvo, mas não foi possível carregar a lista atualizada. Suas alterações estão salvas.'],
  spanishContent:['ES · Content in Spanish','ES · Contenido en español','ES · Conteúdo em espanhol'],
  resources:['Resources','Recursos','Recursos'],
  skip:['Skip to content','Ir al contenido','Ir para o conteúdo'],loading:['Loading…','Cargando…','Carregando…'],retry:['Try again','Reintentar','Tentar novamente'],
  intro:['Connect with the people shaping our cities. Choose your conference blocks and manage your FIIU participation in NODAL.','Conecta con quienes transforman nuestras ciudades. Elige tus bloques de conferencias y gestiona tu participación en FIIU desde NODAL.','Conecte-se com quem transforma nossas cidades. Escolha seus blocos de conferências e gerencie sua participação no FIIU pela NODAL.'],
  dates:['20–25 October 2026','20–25 de octubre de 2026','20–25 de outubro de 2026'],register:['Register','Inscríbete','Inscreva-se'],website:['Festival website','Web del festival','Site do festival'],officialProgram:['View the live programme','Ver el programa en vivo','Ver a programação ao vivo'],
  programmeTitle:['Make room for the city','Haz espacio para la ciudad','Abra espaço para a cidade'],programmeHint:['Times are in Lima. The programme may change; admission is subject to each venue’s capacity.','Horarios de Lima. El programa está sujeto a cambios y el ingreso depende del aforo de cada espacio.','Horários de Lima. A programação pode mudar e a entrada depende da capacidade de cada espaço.'],
  morning:['Morning block','Bloque de mañana','Bloco da manhã'],evening:['Evening block','Bloque de noche','Bloco da noite'],lab:['Public-officials laboratory','Laboratorio para funcionarios','Laboratório para gestores públicos'],workshop:['Workshops','Talleres','Oficinas'],route:['Urban routes','Rutas urbanas','Roteiros urbanos'],venuePending:['Venue to be confirmed','Lugar por confirmar','Local a confirmar'],timePending:['Time to be confirmed','Horario por confirmar','Horário a confirmar'],
  external:['Separate registration','Inscripción independiente','Inscrição separada'],party:['Closing party','Fiesta de cierre','Festa de encerramento'],
  registration:['Your FIIU registration','Tu inscripción al FIIU','Sua inscrição no FIIU'],signinHint:['Use your NODAL account to register. Your registration stays in your console, where you can review and update it.','Usa tu cuenta de NODAL para inscribirte. Tu inscripción queda en Mi panel para revisarla y actualizarla.','Use sua conta NODAL para se inscrever. Sua inscrição fica no painel, onde você pode consultar e atualizar.'],signin:['Sign in or create an account','Inicia sesión o crea tu cuenta','Entre ou crie sua conta'],
  personal:['About you','Tus datos','Seus dados'],choices:['Choose your activities','Elige tus actividades','Escolha suas atividades'],questionnaire:['A few questions','Algunas preguntas','Algumas perguntas'],privateHint:['Only you, the FIIU organising team and NODAL administrators can see these answers. They are not published on your NODAL profile.','Solo tú, el equipo organizador del FIIU y la administración de NODAL pueden ver estas respuestas. No se publican en tu perfil de NODAL.','Apenas você, a equipe organizadora do FIIU e a administração da NODAL podem ver estas respostas. Elas não são publicadas no seu perfil NODAL.'],
  firstName:['First name','Nombres','Nome'],lastName:['Last name','Apellidos','Sobrenome'],email:['Account email','Correo de tu cuenta','E-mail da conta'],country:['Country of origin','País de origen','País de origem'],city:['City of residence','Ciudad de residencia','Cidade de residência'],profile:['Your main profile','Tu perfil principal','Seu perfil principal'],
  choose:['Select an option','Selecciona una opción','Selecione uma opção'],student:['Student','Estudiante','Estudante'],academic:['Academic','Académico/a','Acadêmico/a'],researcher:['Researcher','Investigador/a','Pesquisador/a'],professional:['Private-sector professional','Profesional del sector privado','Profissional do setor privado'],entrepreneur:['Entrepreneur','Emprendedor/a','Empreendedor/a'],activist:['Activist / community leader','Activista / líder comunitario','Ativista / liderança comunitária'],organization:['Organisation / collective member','Miembro de organización / colectivo','Membro de organização / coletivo'],public_official:['Public official','Funcionario/a público/a','Gestor/a público/a'],other:['Other','Otro','Outro'],
  publicOfficial:['Are you currently a public official?','¿Actualmente eres funcionario/a público/a?','Você é atualmente gestor/a público/a?'],yes:['Yes','Sí','Sim'],no:['No','No','Não'],
  applyLab:['Apply for the 20 October laboratory','Postular al laboratorio del 20 de octubre','Candidatar-se ao laboratório de 20 de outubro'],labHint:['For public officials from local governments. Applications are reviewed by the organisers; applying does not confirm admission. Supported by CAF, Fundación FEMSA and UNACEM.','Dirigido a funcionarios de gobiernos locales. El equipo revisará las postulaciones; postular no confirma el ingreso. Promovido junto con CAF, Fundación FEMSA y UNACEM.','Para gestores de governos locais. A equipe analisa as candidaturas; candidatar-se não confirma a admissão. Promovido com CAF, Fundación FEMSA e UNACEM.'],institution:['Institution you represent','Institución a la que representas','Instituição que representa'],position:['Department and role','Área y cargo profesional','Área e cargo profissional'],
  nationalId:['National ID','Cédula o DNI','Documento de identidade'],gender:['Gender','Género','Gênero'],female:['Female','Femenino','Feminino'],male:['Male','Masculino','Masculino'],prefer_not:['Prefer not to say','Prefiero no responder','Prefiro não responder'],age:['Age','Edad','Idade'],accessibility:['Accessibility support','Apoyo de accesibilidad','Apoio de acessibilidade'],none:['No additional support','No necesito apoyo adicional','Não preciso de apoio adicional'],mobility:['Mobility support','Apoyo en movilidad','Apoio de mobilidade'],visual:['Visual adaptations','Adaptaciones visuales','Adaptações visuais'],hearing:['Hearing adaptations','Adaptaciones auditivas','Adaptações auditivas'],communication:['Communication or cognitive support','Apoyo de comunicación o cognitivo','Apoio de comunicação ou cognitivo'],accessibilityOther:['Describe the support you need','Describe el apoyo que necesitas','Descreva o apoio de que precisa'],
  motivation:['Main motivation','Motivación principal','Motivação principal'],learn:['Learn about citizenship and urbanism','Aprender sobre ciudadanía y urbanismo','Aprender sobre cidadania e urbanismo'],career:['Professional development','Desarrollo profesional','Desenvolvimento profissional'],network:['Meet and connect with people','Conocer y conectar con personas','Conhecer e conectar pessoas'],explore:['Discover the city','Descubrir la ciudad','Conhecer a cidade'],motivationOther:['Describe your other motivation','Describe tu otra motivación','Descreva sua outra motivação'],previousAttendance:['Have you attended FIIU before?','¿Has participado en ediciones anteriores?','Já participou de outras edições?'],all:['Every edition','Todas las ediciones','Todas as edições'],some:['Some editions','Algunas ediciones','Algumas edições'],
  privacyAccepted:['I agree to share these answers with the FIIU organising team and NODAL administrators to manage my participation and any accessibility support I request.','Acepto compartir estas respuestas con el equipo organizador del FIIU y la administración de NODAL para gestionar mi participación y el apoyo de accesibilidad que solicite.','Concordo em compartilhar estas respostas com a equipe organizadora do FIIU e a administração da NODAL para gerenciar minha participação e o apoio de acessibilidade solicitado.'],privacy:['Read the privacy policy','Leer la política de privacidad','Ler a política de privacidade'],save:['Save my registration','Guardar mi inscripción','Salvar minha inscrição'],saving:['Saving…','Guardando…','Salvando…'],saved:['Your registration is saved','Tu inscripción está guardada','Sua inscrição está salva'],savedHint:['This is your saved registration. Admission remains subject to venue capacity.','Esta es tu inscripción guardada. El ingreso sigue sujeto al aforo de cada espacio.','Esta é sua inscrição salva. A entrada continua sujeita à capacidade de cada espaço.'],edit:['Edit registration','Editar inscripción','Editar inscrição'],cancel:['Cancel registration','Cancelar inscripción','Cancelar inscrição'],cancelConfirm:['Cancel your registration and remove its answers and attendance badges?','¿Cancelar tu inscripción y eliminar sus respuestas e insignias de asistencia?','Cancelar sua inscrição e remover suas respostas e insígnias de presença?'],cancelled:['Your registration was cancelled.','Tu inscripción fue cancelada.','Sua inscrição foi cancelada.'],
  badges:['Participation badges','Insignias de participación','Insígnias de participação'],badgesHint:['Badges appear when you check in with the session QR code or the team confirms your attendance. Registration alone does not earn a badge.','Las insignias aparecen cuando registras tu asistencia con el código QR de la sesión o el equipo la confirma. La inscripción por sí sola no otorga insignias.','As insígnias aparecem quando você registra presença com o QR code da sessão ou a equipe a confirma. A inscrição sozinha não gera insígnia.'],
  adminInvalid:['Check the required fields and use HTTPS for links.','Revisa los campos obligatorios y utiliza HTTPS en los enlaces.','Revise os campos obrigatórios e use HTTPS nos links.'],editorConflict:['Another organizer changed this information. Reload to review the latest version before saving again.','Otro organizador cambió esta información. Recarga para revisar la versión actual antes de guardar de nuevo.','Outro organizador alterou estas informações. Recarregue para conferir a versão atual antes de salvar novamente.'],
  error:['We could not complete the request. Your answers are still here. Try again.','No pudimos completar la solicitud. Tus respuestas siguen aquí. Intenta de nuevo.','Não foi possível concluir a solicitação. Suas respostas continuam aqui. Tente novamente.'],invalid:['Review the required fields and choose a conference, a workshop or route interest, or apply for the laboratory.','Revisa los campos obligatorios y elige una conferencia, un taller o ruta de interés, o postula al laboratorio.','Revise os campos obrigatórios e escolha uma conferência, uma oficina ou roteiro de interesse, ou candidate-se ao laboratório.'],conflict:['This registration changed in another window. Your draft is still here. Review the saved version before replacing it.','Esta inscripción cambió en otra ventana. Tu borrador sigue aquí. Revisa la versión guardada antes de reemplazarla.','Esta inscrição mudou em outra janela. Seu rascunho continua aqui. Revise a versão salva antes de substituí-la.'],viewSaved:['Review saved registration','Revisar inscripción guardada','Revisar inscrição salva'],useLatest:['Use the current version for my next save','Usar la versión actual para mi próximo guardado','Usar a versão atual no próximo salvamento'],closed:['Registration is currently closed.','La inscripción está cerrada por ahora.','As inscrições estão fechadas no momento.'],unauthorized:['Sign in again to continue. Your draft stays here.','Vuelve a iniciar sesión para continuar. Tu borrador queda aquí.','Entre novamente para continuar. Seu rascunho permanece aqui.'],forbidden:['This action is not available for your account.','Esta acción no está disponible para tu cuenta.','Esta ação não está disponível para sua conta.'],rate:['Please wait a minute before trying again.','Espera un minuto antes de volver a intentarlo.','Aguarde um minuto antes de tentar novamente.'],
  news:['Festival news','Noticias del festival','Notícias do festival'],noNews:['Festival updates will appear here when the team publishes them.','Las novedades aparecerán aquí cuando el equipo las publique.','As novidades aparecerão aqui quando a equipe publicar.'],materials:['Recordings and materials','Grabaciones y materiales','Gravações e materiais'],noMaterials:['Recordings and materials will be shared here during and after the festival.','Las grabaciones y los materiales se compartirán aquí durante y después del festival.','Gravações e materiais serão compartilhados aqui durante e depois do festival.'],open:['Open link','Abrir enlace','Abrir link'],recording:['Recording','Grabación','Gravação'],material:['Material','Material','Material'],newsKind:['News','Noticia','Notícia'],admin:['Organiser dashboard','Panel de organización','Painel da organização'],participants:['Participants','Participantes','Participantes'],export:['Download registrations CSV','Descargar inscripciones CSV','Baixar inscrições CSV'],loadMore:['Load more','Cargar más','Carregar mais'],details:['View details','Ver detalles','Ver detalhes'],noParticipants:['No registrations yet.','Aún no hay inscripciones.','Ainda não há inscrições.'],review:['Laboratory review','Revisión del laboratorio','Análise do laboratório'],reviewPending:['Pending','Pendiente','Pendente'],reviewAccepted:['Accepted','Aceptada','Aceita'],reviewDeclined:['Not selected','No seleccionada','Não selecionada'],saveReview:['Save review','Guardar revisión','Salvar análise'],attendance:['Confirm attendance','Confirmar asistencia','Confirmar presença'],attendanceHint:['QR check-ins appear here on their own. Tick attendance the team has verified, or untick one to correct it.','Los registros por QR aparecen aquí solos. Marca la asistencia que el equipo verificó o desmárcala para corregirla.','Os registros por QR aparecem aqui sozinhos. Marque a presença que a equipe verificou ou desmarque para corrigi-la.'],
  settings:['Registration and links','Inscripción y enlaces','Inscrição e links'],registrationOpen:['Accept registrations','Aceptar inscripciones','Aceitar inscrições'],programUrl:['Official programme URL','Enlace del programa oficial','Link da programação oficial'],workshopsUrl:['Workshop registration URL','Enlace de inscripción a talleres','Link de inscrição nas oficinas'],routesUrl:['Urban route registration URL','Enlace de inscripción a rutas','Link de inscrição nos roteiros'],partyUrl:['Closing party registration URL','Enlace de inscripción a la fiesta','Link de inscrição na festa'],saveSettings:['Save settings','Guardar configuración','Salvar configurações'],changesSaved:['Changes saved.','Cambios guardados.','Alterações salvas.'],content:['News and materials','Noticias y materiales','Notícias e materiais'],newContent:['New publication','Nueva publicación','Nova publicação'],title:['Title','Título','Título'],body:['Text','Texto','Texto'],kind:['Type','Tipo','Tipo'],url:['HTTPS link','Enlace HTTPS','Link HTTPS'],activityId:['Related activity','Actividad relacionada','Atividade relacionada'],status:['Publication status','Estado de publicación','Status de publicação'],draft:['Draft','Borrador','Rascunho'],published:['Published','Publicado','Publicado'],archived:['Archived','Archivado','Arquivado'],saveContent:['Save publication','Guardar publicación','Salvar publicação'],editContent:['Edit publication','Editar publicación','Editar publicação'],
  registrationOpenNow:['Registration open','Inscripciones abiertas','Inscrições abertas'],registrationClosedNow:['Registration closed','Inscripciones cerradas','Inscrições encerradas'],
  conferenceOne:['conference block','bloque de conferencias','bloco de conferências'],conferenceMany:['conference blocks','bloques de conferencias','blocos de conferências'],
  workshopOne:['workshop','taller','oficina'],workshopMany:['workshops','talleres','oficinas'],
  routeOne:['urban route','ruta urbana','roteiro urbano'],routeMany:['urban routes','rutas urbanas','roteiros urbanos'],
  labOne:['laboratory for public officials','laboratorio para funcionarios','laboratório para gestores públicos'],
  interestOne:['interest','interés','interesse'],interestMany:['interests','intereses','interesses'],
  sessionOne:['session','sesión','sessão'],sessions:['sessions','sesiones','sessões'],
  viewRegistration:['View my registration','Ver mi inscripción','Ver minha inscrição'],viewProgramme:['Explore the programme','Explorar el programa','Explorar a programação'],
  signinClosedHint:['Already registered? Sign in with your NODAL account to review your registration.','¿Ya te inscribiste? Inicia sesión con tu cuenta de NODAL para revisar tu inscripción.','Já se inscreveu? Entre com sua conta NODAL para consultar sua inscrição.'],
  startingPoint:['Starting point:','Punto de inicio:','Ponto de partida:'],saveFailed:['Not saved. See the message above.','No se guardó. Revisa el mensaje de arriba.','Não foi salvo. Veja a mensagem acima.'],
  statusRegistered:['Registered','Inscrito/a','Inscrito/a'],statusNotRegistered:['Not registered yet','Aún sin inscripción','Ainda sem inscrição'],
  actionNeeded:['Action needed','Acción necesaria','Ação necessária'],
  datesMonth:['October 2026','Octubre 2026','Outubro 2026'],nextForYou:['Next for you','Lo próximo para ti','Próximo para você'],latestUpdate:['Latest update','Última novedad','Última novidade'],
  pendingShort:['Lab: in review','Laboratorio: en revisión','Laboratório: em análise'],acceptedShort:['Lab: accepted','Laboratorio: aceptada','Laboratório: aceita'],declinedShort:['Lab: not selected','Laboratorio: no seleccionada','Laboratório: não selecionada'],
  pendingHint:['The organising team is reviewing applications. The decision will appear here.','El equipo organizador está revisando las postulaciones. La decisión aparecerá aquí.','A equipe organizadora está analisando as candidaturas. A decisão aparecerá aqui.'],
  acceptedHint:['Your place in the 20 October laboratory is confirmed.','Tu lugar en el laboratorio del 20 de octubre está confirmado.','Sua vaga no laboratório de 20 de outubro está confirmada.'],
  declinedHint:['Your application was not selected this time. Your other registrations are unchanged.','Tu postulación no fue seleccionada esta vez. Tus demás inscripciones no cambian.','Sua candidatura não foi selecionada desta vez. Suas demais inscrições continuam iguais.'],
  dayNav:['Festival days','Días del festival','Dias do festival'],
  workshopType:['Workshop','Taller','Oficina'],routeType:['Urban route','Ruta urbana','Roteiro urbano'],
  addToRegistration:['Add to my registration','Añadir a mi inscripción','Adicionar à minha inscrição'],saveInterest:['Save as interest','Guardar como interés','Salvar como interesse'],
  interestChip:['Interest saved','Interés guardado','Interesse salvo'],activityForm:['Activity form','Formulario de la actividad','Formulário da atividade'],
  externalFormNext:['Next step: complete the activity form','Siguiente paso: completa el formulario de la actividad','Próximo passo: preencha o formulário da atividade'],
  newTab:['(opens in a new tab)','(se abre en una pestaña nueva)','(abre em uma nova aba)'],
  partyRegister:['Register for the closing party','Inscríbete en la fiesta de cierre','Inscreva-se na festa de encerramento'],partyDetails:['Closing party details','Detalles de la fiesta de cierre','Detalhes da festa de encerramento'],
  formIntro:['Takes about 5 minutes. Fields marked * are required.','Toma unos 5 minutos. Los campos marcados con * son obligatorios.','Leva cerca de 5 minutos. Os campos marcados com * são obrigatórios.'],
  formDuration:['Registration takes about 5 minutes.','La inscripción toma unos 5 minutos.','A inscrição leva cerca de 5 minutos.'],
  canConferences:['Choose your conference blocks','Elige tus bloques de conferencias','Escolha seus blocos de conferências'],
  canLab:['Apply for the laboratory for public officials','Postula al laboratorio para funcionarios','Candidate-se ao laboratório para gestores públicos'],
  canInterests:['Save workshop and urban route interests','Guarda talleres y rutas urbanas de interés','Salve oficinas e roteiros de interesse'],
  stepsLabel:['Registration steps','Pasos de la inscripción','Etapas da inscrição'],consentStep:['Accessibility and consent','Accesibilidad y consentimiento','Acessibilidade e consentimento'],
  // Short step names for the sticky step bar; the fieldset legends keep the full wording.
  stepChoices:['Activities','Actividades','Atividades'],stepQuestions:['Questions','Preguntas','Perguntas'],stepConsent:['Consent','Consentimiento','Consentimento'],
  choiceAdded:['Selected · save to confirm','Seleccionado · guarda para confirmar','Selecionado · salve para confirmar'],
  requiredGroup:[' (required)',' (obligatorio)',' (obrigatório)'],
  choicesHint:['Choose at least one conference block, workshop or route interest, or the laboratory. Times are in Lima.','Elige al menos un bloque de conferencias, un taller o ruta de interés, o el laboratorio. Horarios de Lima.','Escolha pelo menos um bloco de conferências, uma oficina ou roteiro de interesse, ou o laboratório. Horários de Lima.'],
  labQuestionHint:['Public officials who answer Yes can apply for the 20 October laboratory.','Si respondes Sí, podrás postular al laboratorio del 20 de octubre.','Se responder Sim, você poderá se candidatar ao laboratório de 20 de outubro.'],
  labApplied:['lab application','postulación al laboratorio','candidatura ao laboratório'],selectionNone:['Nothing selected yet','Aún no has elegido nada','Nada selecionado ainda'],
  backToSaved:['Back to my registration','Volver a mi inscripción','Voltar para minha inscrição'],
  requiredField:['Answer this question to continue.','Responde esta pregunta para continuar.','Responda a esta pergunta para continuar.'],
  privacyRequired:['Confirm this to save your registration.','Confirma esta casilla para guardar tu inscripción.','Confirme esta opção para salvar sua inscrição.'],
  invalidAge:['Enter your age as a whole number between 1 and 120.','Escribe tu edad como un número entero entre 1 y 120.','Informe sua idade como um número inteiro entre 1 e 120.'],
  chooseActivity:['Choose a conference block, save a workshop or route interest, or apply for the laboratory.','Elige un bloque de conferencias, guarda un taller o ruta de interés, o postula al laboratorio.','Escolha um bloco de conferências, salve uma oficina ou roteiro de interesse, ou candidate-se ao laboratório.'],
  reviewErrors:['Some answers need attention. The first one is highlighted.','Algunas respuestas necesitan revisión. La primera está resaltada.','Algumas respostas precisam de revisão. A primeira está destacada.'],
  answersNeedAttention:['Some answers need attention','Algunas respuestas necesitan revisión','Algumas respostas precisam de revisão'],
  stepDone:['completed','completado','concluída'],
  latestReplace:['Your next save will replace the saved version with this draft.','Al guardar, este borrador reemplazará la versión guardada.','Ao salvar, este rascunho substituirá a versão salva.'],
  latestCreate:['The saved registration no longer exists. Your next save will register you again with this draft.','La inscripción guardada ya no existe. Al guardar, te inscribirás de nuevo con este borrador.','A inscrição salva não existe mais. Ao salvar, você fará uma nova inscrição com este rascunho.'],
  labType:['Laboratory for public officials · by application','Laboratorio para funcionarios · con postulación','Laboratório para gestores públicos · com candidatura'],
  loadError:['We could not load the festival information. Try again.','No pudimos cargar la información del festival. Intenta de nuevo.','Não foi possível carregar as informações do festival. Tente novamente.'],
  hubMaterials:['Recordings and materials will appear on the FIIU page as the team shares them.','Las grabaciones y los materiales aparecerán en la página del FIIU cuando el equipo los comparta.','Gravações e materiais aparecerão na página do FIIU quando a equipe compartilhar.'],
  incompleteNotice:['Action needed: some required answers are missing. Edit your registration to complete them.','Acción necesaria: faltan algunas respuestas obligatorias. Edita tu inscripción para completarlas.','Ação necessária: faltam algumas respostas obrigatórias. Edite sua inscrição para completá-las.'],
  incompleteClosedNotice:['Action needed: some required answers are missing. Registration is closed, so write to fiiu@ocupatucalle.com to complete them.','Acción necesaria: faltan algunas respuestas obligatorias. La inscripción está cerrada: escribe a fiiu@ocupatucalle.com para completarlas.','Ação necessária: faltam algumas respostas obrigatórias. As inscrições estão encerradas: escreva para fiiu@ocupatucalle.com para completá-las.'],
  badgesHintShort:['Badges appear when you check in with the session QR code.','Las insignias aparecen al registrar tu asistencia con el QR de la sesión.','As insígnias aparecem ao registrar presença com o QR da sessão.'],
  myPlan:['Your programme','Tu programa','Sua programação'],
  allNews:['All festival news','Todas las noticias del festival','Todas as notícias do festival'],
  watchRecording:['Watch recording','Ver grabación','Assistir à gravação'],openMaterial:['Open material','Abrir material','Abrir material'],
  // Organiser dashboard and member dashboard widget.
  navOverview:['Overview','Resumen','Visão geral'],sectionNav:['Sections','Secciones','Seções'],viewPublic:['View public page','Ver página pública','Ver página pública'],
  exportNote:['Contains private answers (ID, accessibility). Store it securely and delete it after the festival.','Contiene respuestas privadas (documento, accesibilidad). Guárdalo de forma segura y elimínalo después del festival.','Contém respostas privadas (documento, acessibilidade). Guarde com segurança e exclua após o festival.'],
  labApplications:['Laboratory applications','Postulaciones al laboratorio','Candidaturas ao laboratório'],reviewPendingAction:['Review pending applications','Revisar postulaciones pendientes','Analisar candidaturas pendentes'],
  updatedAt:['Updated','Actualizado','Atualizado'],
  peopleWithPlans:['People with plans','Personas con planes','Pessoas com planos'],
  byDayHint:['Each person counts once per day, whether they registered for a conference, applied for the laboratory or saved a workshop or route interest.','Cada persona cuenta una vez por día, ya sea por inscribirse en una conferencia, postular al laboratorio o guardar un taller o ruta de interés.','Cada pessoa conta uma vez por dia, seja por se inscrever em uma conferência, candidatar-se ao laboratório ou salvar uma oficina ou roteiro de interesse.'],
  conferencesAndLab:['Conferences and laboratory','Conferencias y laboratorio','Conferências e laboratório'],interested:['Interested','Interesados','Interessados'],
  registeredShort:['Reg.','Inscr.','Inscr.'],attendedShort:['Att.','Asist.','Pres.'],interestedShort:['Interest','Interés','Interesse'],peopleWithPlansShort:['People','Personas','Pessoas'],
  searchParticipants:['Search by name or email','Buscar por nombre o correo','Buscar por nome ou e-mail'],filterLabel:['Filter participants','Filtrar participantes','Filtrar participantes'],
  filterAll:['All','Todos','Todos'],filterLabPending:['Lab: pending','Laboratorio: pendientes','Laboratório: pendentes'],filterLabAccepted:['Lab: accepted','Laboratorio: aceptadas','Laboratório: aceitas'],
  participantShownOne:['participant shown','participante mostrado','participante exibido'],participantShownMany:['participants shown','participantes mostrados','participantes exibidos'],
  showingLoaded:['Showing people loaded so far. Load more to search everyone.','Se muestran las personas cargadas hasta ahora. Carga más para buscar entre todas.','Mostrando as pessoas carregadas até agora. Carregue mais para buscar entre todas.'],
  noMatches:['No participants match this search or filter.','Ningún participante coincide con esta búsqueda o filtro.','Nenhum participante corresponde a esta busca ou filtro.'],showAll:['Show everyone','Mostrar a todas las personas','Mostrar todas as pessoas'],
  autoRefresh:['Refresh every minute','Actualizar cada minuto','Atualizar a cada minuto'],
  selectParticipant:['Select a participant to see their answers, lab review and attendance.','Selecciona un participante para ver sus respuestas, la revisión del laboratorio y la asistencia.','Selecione um participante para ver suas respostas, a análise do laboratório e a presença.'],
  backToList:['Back to the list','Volver a la lista','Voltar para a lista'],allAnswers:['All answers','Todas las respuestas','Todas as respostas'],
  profileAdmin:['Profile','Perfil','Perfil'],publicOfficialAdmin:['Public official','Funcionario/a público/a','Gestor/a público/a'],applyLabAdmin:['Laboratory application','Postulación al laboratorio','Candidatura ao laboratório'],institutionAdmin:['Institution','Institución','Instituição'],
  previousAttendanceAdmin:['Previous editions','Ediciones anteriores','Edições anteriores'],accessibilityOtherAdmin:['Support details','Detalle del apoyo','Detalhes do apoio'],motivationOtherAdmin:['Other motivation','Otra motivación','Outra motivação'],
  externalInterestAdminHint:['Interest only. Facilitators register people through their own Google Form.','Solo interés. Cada facilitador inscribe a las personas con su propio Google Form.','Apenas interesse. Cada facilitador inscreve as pessoas pelo próprio Google Forms.'],
  showId:['Show','Mostrar','Mostrar'],hideId:['Hide','Ocultar','Ocultar'],
  otherActivities:['Other workshops and routes this day','Otros talleres y rutas de este día','Outras oficinas e roteiros deste dia'],
  attendanceSaved:['Saved','Guardado','Salvo'],reloadLatest:['Reload the latest version','Recargar la versión actual','Recarregar a versão atual'],
  closeConfirm:['Close registration? New people will not be able to register; saved registrations stay.','¿Cerrar la inscripción? Nadie nuevo podrá inscribirse; las inscripciones guardadas se mantienen.','Encerrar as inscrições? Novas pessoas não poderão se inscrever; as inscrições salvas continuam.'],
  registrationOpenHint:['When closed, new people cannot register. Saved registrations stay.','Cuando está cerrada, nadie nuevo puede inscribirse. Las inscripciones guardadas se mantienen.','Quando encerrada, novas pessoas não podem se inscrever. As inscrições salvas continuam.'],
  publicLinks:['Links shown on the public page','Enlaces que se muestran en la página pública','Links exibidos na página pública'],
  cancelEdit:['Cancel editing','Cancelar edición','Cancelar edição'],discardEdit:['Discard your unsaved changes to this publication?','¿Descartar los cambios sin guardar de esta publicación?','Descartar as alterações não salvas desta publicação?'],
  pendingReviewOne:['application pending review','postulación pendiente de revisión','candidatura pendente de análise'],pendingReviewMany:['applications pending review','postulaciones pendientes de revisión','candidaturas pendentes de análise'],
  communityTitle:['A community that meets','Una comunidad que se encuentra','Uma comunidade que se encontra'],communityIntro:['Meet people, share experiences and build connections through the city.','Encuentra personas, comparte experiencias y crea vínculos a través de la ciudad.','Encontre pessoas, compartilhe experiências e crie conexões pela cidade.'],chelas:['Chelas urbanas','Chelas urbanas','Chelas urbanas'],chelasHint:['Explore local learning circles and meetups. To propose an urban meetup, contact the NODAL team.','Explora círculos de aprendizaje y encuentros locales. Para proponer una chela urbana, contacta al equipo NODAL.','Explore círculos de aprendizagem e encontros locais. Para propor um encontro urbano, fale com a equipe NODAL.'],organize:['Propose an urban meetup','Proponer una chela urbana','Propor um encontro urbano'],events:['Community events','Eventos de la comunidad','Eventos da comunidade'],circles:['Explore learning circles','Explorar círculos de aprendizaje','Explorar círculos de aprendizagem'],people:['Meet the network','Conoce la red','Conheça a rede'],resourcesTitle:['Ideas and opportunities to put into practice','Ideas y oportunidades para llevar a la práctica','Ideias e oportunidades para colocar em prática'],opportunities:['Explore opportunities','Explorar oportunidades','Explorar oportunidades'],knowledgeTitle:['Knowledge we build together','Conocimiento que construimos juntos','Conhecimento que construímos juntos'],courses:['Courses','Cursos','Cursos'],coursesHint:['Learn with the community, access sessions and share your work.','Aprende con la comunidad, accede a sesiones y comparte tu trabajo.','Aprenda com a comunidade, acesse sessões e compartilhe seu trabalho.'],masterclasses:['Masterclasses and resources','Masterclasses y recursos','Masterclasses e recursos'],masterclassesHint:['Explore published resources, case studies and shared knowledge.','Explora recursos publicados, casos de estudio y conocimiento compartido.','Explore recursos publicados, estudos de caso e conhecimento compartilhado.'],browseResources:['Browse resources','Explorar recursos','Explorar recursos'],
  // QR check-in: the attendee page (fiiu-checkin.html), the screen shown at the door (fiiu-qr.html) and the organiser views.
  checkinPage:['Session check-in','Registro de asistencia','Registro de presença'],checking:['Checking you in…','Registrando tu asistencia…','Registrando sua presença…'],
  checkedInTitle:['You’re checked in','Tu asistencia quedó registrada','Sua presença foi registrada'],alreadyCheckedIn:['You were already checked in','Tu asistencia ya estaba registrada','Sua presença já estava registrada'],checkedInAt:['Checked in at','Registrada a las','Registrada às'],checkedInOn:['Checked in on','Registrada el','Registrada em'],atClock:['at','a las','às'],
  scanAgainTitle:['Scan the code again to check in','Vuelve a escanear el código para registrar tu asistencia','Escaneie o código de novo para registrar sua presença'],scanAgainHint:['No check-in is recorded for this block yet. Scan the screen, or type the 6-character code shown under the QR.','Aún no hay asistencia registrada en este bloque. Escanea la pantalla o escribe el código de 6 caracteres que aparece debajo del QR.','Ainda não há presença registrada neste bloco. Escaneie a tela ou digite o código de 6 caracteres que aparece embaixo do QR.'],
  signInScanAgainHint:['Use the account you registered with. After signing in, scan the screen again or type its new code: codes change every minute.','Usa la cuenta con la que te inscribiste. Después de iniciar sesión, vuelve a escanear la pantalla o escribe su código nuevo: los códigos cambian cada minuto.','Use a conta com que você se inscreveu. Depois de entrar, escaneie a tela de novo ou digite o código novo dela: os códigos mudam a cada minuto.'],
  invalidLink:['This check-in link is incomplete','Este enlace de registro está incompleto','Este link de registro está incompleto'],invalidLinkHint:['Scan the code on the screen again, or type the 6-character code shown under it.','Vuelve a escanear el código de la pantalla o escribe el código de 6 caracteres que aparece debajo.','Escaneie de novo o código da tela ou digite o código de 6 caracteres que aparece embaixo dele.'],
  codeEntry:['Type the code from the screen','Escribe el código de la pantalla','Digite o código da tela'],codeEntryHint:['Use this if your camera cannot read the QR code. The code is under it on the check-in screen.','Úsalo si la cámara no lee el código QR. El código aparece debajo del QR en la pantalla de registro.','Use se a câmera não ler o QR code. O código aparece embaixo dele na tela de registro.'],
  checkinCode:['Code on the screen','Código de la pantalla','Código da tela'],checkinCodeInvalid:['Enter the 6 characters shown on the screen.','Escribe los 6 caracteres que aparecen en la pantalla.','Digite os 6 caracteres que aparecem na tela.'],checkinSubmit:['Check in','Registrar asistencia','Registrar presença'],
  noCheckin:['This activity has no NODAL check-in','Esta actividad no tiene registro de asistencia en NODAL','Esta atividade não tem registro de presença na NODAL'],noCheckinHint:['Check-in is for the 20 October laboratory and the conference blocks. Workshops and routes take attendance with their facilitators.','El registro es para el laboratorio del 20 de octubre y los bloques de conferencias. Los talleres y rutas toman la asistencia con sus facilitadores.','O registro é para o laboratório de 20 de outubro e os blocos de conferências. Oficinas e roteiros registram a presença com seus facilitadores.'],
  signInToCheckIn:['Sign in to check in','Inicia sesión para registrar tu asistencia','Entre para registrar sua presença'],signInCheckinHint:['Use the account you registered with. If the code expires meanwhile, scan the screen again.','Usa la cuenta con la que te inscribiste. Si el código vence mientras tanto, vuelve a escanear la pantalla.','Use a conta com que você se inscreveu. Se o código expirar nesse meio-tempo, escaneie a tela de novo.'],
  notRegistered:['You are not registered for FIIU yet','Aún no tienes inscripción al FIIU','Você ainda não tem inscrição no FIIU'],notRegisteredHint:['Register with this account and choose this block, then scan the code again.','Inscríbete con esta cuenta, elige este bloque y vuelve a escanear el código.','Inscreva-se com esta conta, escolha este bloco e escaneie o código de novo.'],
  askDesk:['Ask the registration desk for help.','Pide ayuda en la mesa de registro.','Peça ajuda na mesa de credenciamento.'],
  notInPlan:['This block is not in your registration','Este bloque no está en tu inscripción','Este bloco não está na sua inscrição'],notInPlanHint:['Add it to your registration, then scan the code again.','Añádelo a tu inscripción y vuelve a escanear el código.','Adicione-o à sua inscrição e escaneie o código de novo.'],
  labNotAccepted:['Your laboratory place is not confirmed','Tu lugar en el laboratorio no está confirmado','Sua vaga no laboratório não está confirmada'],labNotAcceptedHint:['Only accepted applications can check in to the laboratory. Ask the registration desk if this looks wrong.','Solo las postulaciones aceptadas pueden registrar asistencia al laboratorio. Consulta en la mesa de registro si crees que es un error.','Apenas candidaturas aceitas podem registrar presença no laboratório. Consulte a mesa de credenciamento se achar que é um erro.'],
  checkinEndedTitle:['Check-in for this block has closed','El registro de este bloque ya cerró','O registro deste bloco já encerrou'],
  checkinFailedTitle:['Check-in did not go through','No se pudo registrar tu asistencia','Não foi possível registrar sua presença'],
  checkinClosing:['Check-in closes','Cierre del registro','Encerramento do registro'],limaTime:['Lima time','hora de Lima','horário de Lima'],
  codeExpired:['This code isn’t valid now','Este código no es válido ahora','Este código não é válido agora'],expired:['This code isn’t valid now. Codes last 5 minutes: scan the screen at the venue again.','Este código no es válido ahora. Los códigos duran 5 minutos: vuelve a escanear la pantalla en la sede.','Este código não é válido agora. Os códigos duram 5 minutos: escaneie a tela no local de novo.'],expiredHint:['Codes last 5 minutes, so a photo of the screen stops working. Scan the screen at the venue again, or check and retype the 6-character code under the QR.','Los códigos duran 5 minutos, así que una foto de la pantalla deja de funcionar. Vuelve a escanear la pantalla en la sede o revisa y escribe de nuevo el código de 6 caracteres que aparece debajo del QR.','Os códigos duram 5 minutos, então uma foto da tela para de funcionar. Escaneie a tela no local de novo ou confira e digite outra vez o código de 6 caracteres que aparece embaixo do QR.'],
  hoursConfirmed:['h confirmed','h confirmadas','h confirmadas'],labHoursPending:['Laboratory hours are added once its length is confirmed.','Las horas del laboratorio se sumarán cuando se confirme su duración.','As horas do laboratório serão somadas quando a duração for confirmada.'],
  qrTitle:['Check-in screens','Pantallas de registro','Telas de registro'],qrListHint:['Open one screen per block on a projector or a tablet at the door. Attendees scan it with their phone camera. It shows no participant data.','Abre una pantalla por bloque en un proyector o una tablet en la entrada. Las personas la escanean con la cámara del celular. No muestra datos de participantes.','Abra uma tela por bloco em um projetor ou tablet na entrada. As pessoas a escaneiam com a câmera do celular. Ela não mostra dados de participantes.'],
  openCheckinScreen:['Open check-in screen','Abrir pantalla de registro','Abrir tela de registro'],scanToCheckIn:['Scan to check in','Escanea para registrar tu asistencia','Escaneie para registrar presença'],orTypeCode:['No camera? Open this address and type the code:','¿Sin cámara? Abre esta dirección y escribe el código:','Sem câmera? Abra este endereço e digite o código:'],
  checkedInOne:['checked in','con asistencia','com presença'],checkedInMany:['checked in','con asistencia','com presença'],fullScreen:['Full screen','Pantalla completa','Tela cheia'],exitFullScreen:['Exit full screen','Salir de pantalla completa','Sair da tela cheia'],allScreens:['All check-in screens','Todas las pantallas de registro','Todas as telas de registro'],
  codeRotates:['The code changes every minute and this screen keeps it current. Keep it open during check-in.','El código cambia cada minuto y esta pantalla lo mantiene al día. Déjala abierta durante el registro.','O código muda a cada minuto e esta tela o mantém atualizado. Deixe-a aberta durante o registro.'],
  checkinOpenUntil:['Check-in open until','Registro abierto hasta las','Registro aberto até'],checkinClosedAt:['Check-in closed at','El registro cerró a las','O registro fechou às'],
  checkinOpenAllDay:['Check-in open until the end of the day, Lima time','Registro abierto hasta el final del día, hora de Lima','Registro aberto até o fim do dia, horário de Lima'],checkinClosedAllDay:['Check-in closed at the end of the day, Lima time','El registro cerró al final del día, hora de Lima','O registro fechou no fim do dia, horário de Lima'],
  qrUnavailable:['The QR code could not be drawn. Attendees can use the address and code below.','No se pudo dibujar el código QR. Las personas pueden usar la dirección y el código de abajo.','Não foi possível desenhar o QR code. As pessoas podem usar o endereço e o código abaixo.'],qrStale:['This code is out of date. Waiting for the connection to come back…','Este código está desactualizado. Esperando que vuelva la conexión…','Este código está desatualizado. Aguardando a conexão voltar…'],
  organisersOnly:['Organisers only','Solo para la organización','Apenas para a organização'],organisersOnlyHint:['This page is for NODAL organisers. Your account does not have organiser access; ask a NODAL administrator if you need it.','Esta página es para la organización de NODAL. Tu cuenta no tiene acceso de organización; pídelo a una persona administradora de NODAL si lo necesitas.','Esta página é para a organização da NODAL. Sua conta não tem acesso de organização; peça a um administrador da NODAL se precisar.'],
  fiiuPage:['Go to the FIIU page','Ir a la página del FIIU','Ir para a página do FIIU'],backToConsole:['Go to my console','Ir a Mi panel','Ir para o painel'],
  adminSignInAgain:['Your session ended. Sign in again in the new tab, then come back: unsaved drafts stay on this page.','Tu sesión terminó. Vuelve a iniciar sesión en la pestaña nueva y regresa: los borradores sin guardar siguen en esta página.','Sua sessão terminou. Entre novamente na nova aba e volte: os rascunhos não salvos continuam nesta página.'],adminSignIn:['Sign in again','Volver a iniciar sesión','Entrar novamente'],
  sessionEnded:['Your session ended','Tu sesión terminó','Sua sessão terminou'],qrSignInAgain:['The code is hidden until you sign in again.','El código queda oculto hasta que vuelvas a iniciar sesión.','O código fica oculto até você entrar novamente.'],
  checkIn:['Check-in','Registro de asistencia','Registro de presença'],checkInHint:['One screen per block. Attendees scan it with their phone camera and sign in; their attendance and badge appear at once. Workshops and routes take attendance with their facilitators.','Una pantalla por bloque. Las personas la escanean con la cámara del celular e inician sesión; su asistencia e insignia aparecen al instante. Los talleres y rutas toman la asistencia con sus facilitadores.','Uma tela por bloco. As pessoas a escaneiam com a câmera do celular e entram na conta; a presença e a insígnia aparecem na hora. Oficinas e roteiros registram a presença com seus facilitadores.'],
  block:['Block','Bloque','Bloco'],venue:['Venue','Lugar','Local'],checkedIn:['Checked in','Con asistencia','Com presença'],byQr:['by QR code','con código QR','com QR code'],
  hoursTitle:['Hours confirmed','Horas confirmadas','Horas confirmadas'],officialsHours:['Public officials:','Funcionarios públicos:','Gestores públicos:'],shareOfRegistrations:['of registrations','de las inscripciones','das inscrições'],
  share:['Share','Proporción','Proporção'],shareShort:['%','%','%'],hours:['Hours','Horas','Horas'],today:['Today','Hoy','Hoje'],lastCheckIn:['Last check-in','Último registro','Último registro'],
  attendedOne:['session attended','sesión con asistencia','sessão com presença'],attendedMany:['sessions attended','sesiones con asistencia','sessões com presença'],certificateHourOne:['certificate hour','hora de certificado','hora de certificado'],certificateHourMany:['certificate hours','horas de certificado','horas de certificado'],
  methodQr:['QR','QR','QR'],methodTeam:['Team','Equipo','Equipe'],
  cancelWithAttendance:['Your confirmed attendance, badges and hours will be removed too.','También se eliminarán tu asistencia confirmada, tus insignias y tus horas.','Sua presença confirmada, suas insígnias e suas horas também serão removidas.'],
  // The registration summary email: the notice after a first save (followed by the address) and the organiser's status line.
  emailSent:['We emailed a summary to','Te enviamos un resumen a','Enviamos um resumo para'],emailNotSent:['Your registration is saved. We could not send the summary email.','Tu inscripción está guardada. No pudimos enviar el correo de resumen.','Sua inscrição está salva. Não foi possível enviar o e-mail de resumo.'],emailDelayed:['Your registration is saved. The summary email may be delayed or may not arrive.','Tu inscripción está guardada. El correo de resumen puede tardar o no llegar.','Sua inscrição está salva. O e-mail de resumo pode demorar ou não chegar.'],
  emailStatus:['Summary email:','Correo de resumen:','E-mail de resumo:'],emailStatusSent:['sent','enviado','enviado'],emailStatusNone:['not sent','no enviado','não enviado'],emailStatusFailed:['could not be sent','no se pudo enviar','não pôde ser enviado'],emailStatusUncertain:['may not have arrived','puede no haber llegado','pode não ter chegado'],emailStatusSkipped:['skipped (test address)','omitido (dirección de prueba)','ignorado (endereço de teste)'],
  // The organiser's summary-email block (fiiu-admin.js): {n}, {sent}, {total}, {failed}, {cap} and {time} are filled in there.
  backfillTitle:['Summary emails','Correos de resumen','E-mails de resumo'],
  backfillHint:['People who registered before the summary email existed, or while sending was off or over its limit, get it from here, once each: in the language they registered in, or in Spanish when the registration is older than the email and no language was saved.','Quienes se inscribieron antes de que existiera el correo de resumen, o mientras el envío estaba desactivado o sobre su límite, lo reciben desde aquí, una sola vez: en el idioma en que se inscribieron, o en español si la inscripción es anterior al correo y no se guardó el idioma.','Quem se inscreveu antes de o e-mail de resumo existir, ou enquanto o envio estava desativado ou acima do limite, o recebe por aqui, uma única vez: no idioma em que se inscreveu, ou em espanhol se a inscrição é anterior ao e-mail e o idioma não foi salvo.'],
  backfillWaitingOne:['1 registration has not received the summary email','1 inscripción no ha recibido el correo de resumen','1 inscrição não recebeu o e-mail de resumo'],backfillWaitingMany:['{n} registrations have not received the summary email','{n} inscripciones no han recibido el correo de resumen','{n} inscrições não receberam o e-mail de resumo'],
  backfillNoneWaiting:['No registration is waiting for the summary email','Ninguna inscripción espera el correo de resumen','Nenhuma inscrição aguarda o e-mail de resumo'],
  backfillSentOne:['1 sent','1 enviado','1 enviado'],backfillSentMany:['{n} sent','{n} enviados','{n} enviados'],backfillFailed:['{n} failed','{n} con error','{n} com erro'],
  backfillUncertainOne:['1 may not have arrived','1 puede no haber llegado','1 pode não ter chegado'],backfillUncertainMany:['{n} may not have arrived','{n} pueden no haber llegado','{n} podem não ter chegado'],
  backfillSkippedOne:['1 test address skipped','1 dirección de prueba omitida','1 endereço de teste ignorado'],backfillSkippedMany:['{n} test addresses skipped','{n} direcciones de prueba omitidas','{n} endereços de teste ignorados'],
  backfillSendOne:['Send the summary to 1 person','Enviar el resumen a 1 persona','Enviar o resumo para 1 pessoa'],backfillSendMany:['Send the summary to {n} people','Enviar el resumen a {n} personas','Enviar o resumo para {n} pessoas'],
  backfillRetry:['Retry failed ({n})','Reintentar los fallidos ({n})','Tentar de novo os com erro ({n})'],
  backfillConfirmOne:['Confirm: send 1 email','Confirmar: enviar 1 correo','Confirmar: enviar 1 e-mail'],backfillConfirmMany:['Confirm: send {n} emails','Confirmar: enviar {n} correos','Confirmar: enviar {n} e-mails'],
  backfillConfirmHint:['The summary goes out now, a few emails at a time. You can stop at any time.','El resumen sale ahora, unos pocos correos a la vez. Puedes detener el envío en cualquier momento.','O resumo sai agora, alguns e-mails por vez. Você pode parar o envio a qualquer momento.'],
  backfillCancel:['Cancel','Cancelar','Cancelar'],backfillStop:['Stop','Detener','Parar'],
  backfillProgress:['Sent {sent} of {total}','Enviados {sent} de {total}','Enviados {sent} de {total}'],
  backfillStopping:['stopping after this batch…','se detendrá después de este lote…','vai parar após este lote…'],backfillPausing:['pausing half a minute for the request limit…','pausa de medio minuto por el límite de solicitudes…','pausa de meio minuto pelo limite de solicitações…'],
  backfillDone:['Sent {sent} · Failed {failed}','Enviados {sent} · Con error {failed}','Enviados {sent} · Com erro {failed}'],backfillDoneRetry:['you can retry the failed ones','puedes reintentar los que fallaron','você pode tentar de novo os que falharam'],
  backfillStopped:['Stopped.','Detenido.','Parado.'],
  backfillCap:['Today’s limit of {cap} summary emails is reached (sign-up emails included). Sending can continue after {time} Lima time.','Se alcanzó el límite de hoy: {cap} correos de resumen (incluidos los de inscripción). Se puede seguir enviando después de las {time}, hora de Lima.','O limite de hoje foi atingido: {cap} e-mails de resumo (incluindo os de inscrição). O envio pode continuar depois das {time}, horário de Lima.'],
  backfillError:['The sending stopped because a request failed. Nobody is emailed twice: press the button again to continue.','El envío se detuvo porque falló una solicitud. Nadie recibe el correo dos veces: vuelve a pulsar el botón para continuar.','O envio parou porque uma solicitação falhou. Ninguém recebe o e-mail duas vezes: pressione o botão de novo para continuar.'],
  backfillSignIn:['Sign in again, then press the button to continue.','Vuelve a iniciar sesión y pulsa el botón para continuar.','Entre novamente e pressione o botão para continuar.'],
  backfillOff:['Summary emails are off. To turn them on, set EMAIL_SMTP_URL and EMAIL_FROM (and PUBLIC_BASE_URL) in Vercel for Production, then redeploy.','Los correos de resumen están desactivados. Para activarlos, configura EMAIL_SMTP_URL y EMAIL_FROM (y PUBLIC_BASE_URL) en Vercel para Production y vuelve a desplegar.','Os e-mails de resumo estão desativados. Para ativá-los, defina EMAIL_SMTP_URL e EMAIL_FROM (e PUBLIC_BASE_URL) na Vercel para Production e publique de novo.'],
  backfillLoadError:['The summary email status could not be loaded.','No se pudo cargar el estado de los correos de resumen.','Não foi possível carregar o status dos e-mails de resumo.'],
 };
 const lang=()=>window.nodalI18n?.lang||document.documentElement.lang||'en';
 const t=key=>rows[key]?.[Math.max(0,['en','es','pt'].indexOf(lang()))]||key;
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 const tr=(tag,key,cls)=>{const n=el(tag,cls,t(key));n.dataset.fiiuText=key;return n;};
 const button=(key,fn,cls='f-button')=>{const b=tr('button',key,cls);b.type='button';if(fn)b.addEventListener('click',fn);return b;};
 const link=(key,href,cls='f-button secondary')=>{const a=tr('a',key,cls);a.href=href;if(/^https:\/\//.test(href)){a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-describedby','f-newtab');}return a;};
 const source=(tag,text,cls)=>{const n=el(tag,cls,text);n.lang='es';n.translate=true;return n;};
 function field(key,{value='',type='text',required=false,options,max=200}={}){
  const wrap=el('label','f-field'),label=tr('span',key),star=el('span','f-required',' *'),input=el(options?'select':type==='textarea'?'textarea':'input');
  input.name=key;input.id='f-'+key;if(!options&&type!=='textarea')input.type=type;
  if(options){const blank=tr('option','choose');blank.value='';input.append(blank);for(const v of options){const opt=tr('option',v);opt.value=v;input.append(opt);}}
  input.value=value??'';if(!options)input.maxLength=max;star.setAttribute('aria-hidden','true');wrap.append(label,star,input);
  const setRequired=on=>{input.required=on;star.hidden=!on;};setRequired(required);
  return {wrap,input,setRequired};
 }
 function check(key,name,value,checked=false){const wrap=el('label','f-check'),input=el('input');input.type='checkbox';input.name=name;input.value=value;input.checked=checked;wrap.append(input,tr('span',key));return{wrap,input};}
 // The server's reason travels with the error: a check-in refusal is told apart by code, and a closed block carries its closesAt.
 const reason=data=>({code:typeof data?.code==='string'?data.code:undefined,activityId:typeof data?.activityId==='string'?data.activityId:undefined,closesAt:data?.closesAt,registrationOpen:typeof data?.registrationOpen==='boolean'?data.registrationOpen:undefined});
 async function api(path,body,method){
  // Safari before 16 (every iOS 15 browser) has no AbortSignal.timeout; there the request simply runs without the 20 s limit.
  let response,data;const signal=typeof AbortSignal!=='undefined'&&typeof AbortSignal.timeout==='function'?AbortSignal.timeout(20000):undefined;
  try{response=await fetch(path,{...(body===undefined?{}:{method:method||'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),...(signal?{signal}:{})});
   try{data=await response.json();}catch(error){if(response.ok)throw error;data={};}
  }
  catch{throw Object.assign(Error(t('error')),{key:'error'});}
  if(!response.ok){const key=response.status===409&&data?.error==='account changed; reload before continuing'?'accountChanged':path.startsWith('/api/admin/')&&response.status===400?'adminInvalid':path.startsWith('/api/admin/')&&response.status===409?'editorConflict':response.status===403&&data?.error==='registration is closed'?'closed':({400:'invalid',401:'unauthorized',403:'forbidden',409:'conflict',410:'expired',429:'rate'})[response.status]||'error';throw Object.assign(Error(t(key)),{key,status:response.status,...reason(data)});}
  if(!data||typeof data!=='object'||Array.isArray(data))throw Object.assign(Error(t('error')),{key:'error'});
  if(path==='/api/fiiu/checkin'&&!['checked_in','already_checked_in','already'].includes(data.result))throw Object.assign(Error(t('error')),{key:'error'});
  if(path==='/api/fiiu/registration'){
   const r=data.registration;
   if(body===undefined&&(!data.user?.id||typeof data.user.email!=='string'||!Array.isArray(data.attendance)||(r!==null&&(!r?.id||!Number.isSafeInteger(r.version)||r.version<1||!r.answers||!Array.isArray(r.answers.activities)))))throw Object.assign(Error(t('error')),{key:'error'});
   if(method==='PUT'&&(!r||typeof r.id!=='string'||!r.id||r.version!==body.version+1||!r.answers||!Array.isArray(r.answers.activities)||(body.registrationId&&r.id!==body.registrationId)||(body.expectedUserId&&r.userId!==body.expectedUserId)))throw Object.assign(Error(t('error')),{key:'error'});
   if(method==='PUT'&&Array.isArray(body.externalActivities)&&(!Array.isArray(r.answers.externalActivities)||JSON.stringify([...new Set(body.externalActivities)].sort())!==JSON.stringify([...new Set(r.answers.externalActivities)].sort())))throw Object.assign(Error(t('error')),{key:'error'});
   if(method==='DELETE'&&data.ok!==true)throw Object.assign(Error(t('error')),{key:'error'});
  }
  return data;
 }
 function status(node,error){node.textContent=t(error?.key||error||'');node.classList.toggle('is-error',error instanceof Error);node.dataset.fiiuText=error?.key||error||'';}
 const LOCALES={en:'en-GB',es:'es-PE',pt:'pt-BR'},DATE_STYLES={long:{weekday:'long',day:'numeric',month:'long'},short:{weekday:'short',day:'numeric',month:'short'},weekday:{weekday:'short'}};
 const locale=()=>LOCALES[lang()]||'en-GB';
 // Building an Intl formatter costs far more than using one, and long lists format thousands of dates, so each locale and style keeps a single instance.
 const formats=new Map(),memo=(id,make)=>formats.get(id)||formats.set(id,make()).get(id);
 const limaFormat=(loc,style,options)=>memo(loc+'|'+style,()=>new Intl.DateTimeFormat(loc,{...options,timeZone:'America/Lima'}));
 const cap=text=>text?text.charAt(0).toLocaleUpperCase(locale())+text.slice(1):text;
 const limaNoon=value=>new Date(value+'T12:00:00-05:00');
 const date=(value,style='long')=>{const key=['short','weekday'].includes(style)?style:'long';return cap(limaFormat(locale(),key,DATE_STYLES[key]).format(limaNoon(value)));};
 function dateRange(start,end){const f=limaFormat(locale(),'range',{day:'numeric',month:'long',year:'numeric'}),a=limaNoon(start),b=limaNoon(end);return f.formatRange?f.formatRange(a,b):f.format(a)+' – '+f.format(b);}
 const limaDate=(value=new Date())=>limaFormat('en-CA','day',{year:'numeric',month:'2-digit',day:'2-digit'}).format(value);
 const limaMinutes=(value=new Date())=>{const [hours,minutes]=limaFormat('en-GB','clock',{hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(value).split(':').map(Number);return hours*60+minutes;};
 function refresh(){
  // The organisers-only page has no script of its own (the server serves it in place of organiser pages), so its tab title is set here.
  if(document.body?.dataset?.page==='organisers-only')document.title='NODAL · '+t('organisersOnly');
  document.querySelectorAll('[data-fiiu-text]').forEach(n=>{n.textContent=t(n.dataset.fiiuText);});
  document.querySelectorAll('[data-fiiu-date]').forEach(n=>{n.textContent=date(n.dataset.fiiuDate,n.dataset.fiiuDateStyle);});
  document.querySelectorAll('[data-fiiu-range]').forEach(n=>{const [a,b]=n.dataset.fiiuRange.split('/');n.textContent=dateRange(a,b);});
 }
 function dateNode(value,tag='p',style='long',cls='f-date'){const n=el(tag,cls,date(value,style));n.dataset.fiiuDate=value;if(style!=='long')n.dataset.fiiuDateStyle=style;return n;}
 function rangeNode(start,end,tag='span',cls='f-range'){const n=el(tag,cls,dateRange(start,end));n.dataset.fiiuRange=start+'/'+end;return n;}
 const PERIODS=['lab','morning','evening','workshop','route'];
 const rank=activity=>{const i=PERIODS.indexOf(activity.period);return i<0?PERIODS.length:i;};
 // Date, then period, then time; Array#sort is stable, so catalog order breaks the remaining ties.
 const chronological=list=>[...list].sort((a,b)=>a.date.localeCompare(b.date)||rank(a)-rank(b)||(a.time||'').localeCompare(b.time||''));
 const typeOf=activity=>activity.registration==='application'?'lab':activity.registration==='general'?'conference':activity.period==='route'?'route':'workshop';
 // The trailing space keeps copied or read-out text as "5 workshops"; in the flex layout it collapses and the gap spaces the parts.
 function countLabel(n,one,many,cls='f-count'){const box=el('span',cls);box.append(el('b','',memo(locale()+'|number',()=>new Intl.NumberFormat(locale())).format(n)+' '),tr('span',n===1?one:many));return box;}
 // A block counts until it ends in Lima ('09:00–13:00' until 13:00); one without a time range, such as the accepted laboratory, counts for its whole day.
 const endsAt=activity=>{const end=/[–-]\s*(\d{1,2}):(\d{2})\s*$/.exec(activity.time||'');return end?Number(end[1])*60+Number(end[2]):24*60;};
 function nextFor(registration,event,now=new Date()){
  const answers=registration?.answers;if(!answers)return null;
  const ids=new Set([...(answers.activities||[]),...(registration.labStatus==='accepted'?event.activities.filter(a=>a.registration==='application').map(a=>a.id):[])]),today=limaDate(now),minutes=limaMinutes(now);
  return chronological(event.activities.filter(a=>ids.has(a.id)&&(a.date>today||(a.date===today&&endsAt(a)>minutes))))[0]||null;
 }
 // Certificate hours: a block counts its scheduled length (the server sends it as minutes; '09:00–13:00' is 240) and an untimed one counts none: the laboratory until
 // its length is set, workshops and routes. Each person's minutes are summed, then rounded half up to whole hours.
 const SPAN=/^(\d{1,2}):(\d{2})\s*[–-]\s*(\d{1,2}):(\d{2})$/;
 const minutesOf=activity=>{if(Number.isFinite(activity?.minutes))return Math.max(0,activity.minutes);const m=SPAN.exec(activity?.time||'');return m?Math.max(0,(m[3]*60+Number(m[4]))-(m[1]*60+Number(m[2]))):0;};
 function hoursOf(attendance,event){const out={sessions:0,minutes:0,hours:0,untimed:[]};for(const record of attendance||[]){const activity=findActivity(event,record.activityId);if(!activity)continue;out.sessions++;const m=minutesOf(activity);if(m)out.minutes+=m;else out.untimed.push(activity.id);}out.hours=Math.round(out.minutes/60);return out;}
 const hoursText=hours=>memo(locale()+'|hours',()=>new Intl.NumberFormat(locale(),{maximumFractionDigits:1})).format(hours)+' h';
 // "6 h confirmed", plus a note while the laboratory's length is unknown; nothing before the first confirmed session.
 function hoursLine(attendance,event,cls='f-hours'){const h=hoursOf(attendance,event);if(!h.sessions)return null;const box=el('p',cls);box.append(countLabel(h.hours,'hoursConfirmed','hoursConfirmed'));if(h.untimed.some(id=>findActivity(event,id)?.registration==='application'))box.append(tr('span','labHoursPending','f-hours-note'));return box;}
 // Check-in has no opening time: a block takes check-ins on any earlier day and until 30 minutes after it ends, in Lima time (UTC−5 all year,
 // no daylight saving); an untimed block until the end of its Lima day. The closing time the server sends wins; the same rule is the fallback.
 function checkinCloses(activity){
  const closes=Date.parse(activity?.checkin?.closesAt);if(Number.isFinite(closes))return closes;
  const m=SPAN.exec(activity.time||''),at=(h,min)=>Date.parse(`${activity.date}T${String(h).padStart(2,'0')}:${min}:00-05:00`);
  return m?at(m[3],m[4])+18e5:at(0,'00')+864e5;
 }
 const checkinState=(activity,now=Date.now())=>now<=checkinCloses(activity)?'open':'closed';
 // Only NODAL's own blocks take QR check-in: the laboratory and the conferences. Workshops and routes stay with their facilitators.
 const checkinActivities=event=>chronological(event.activities.filter(activity=>activity.registration!=='external'));
 const limaClock=value=>limaFormat('en-GB','clock',{hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(value);
 // "Check-in open until 13:30 Lima time", then "Check-in closed at 13:30 Lima time"; the untimed laboratory reads "until the end of the day". The date is added
 // only when check-in closes on another day than the block, since every view already names the block's day. The state class lets a view colour it.
 function windowNode(activity,state=checkinState(activity)){
  const closes=checkinCloses(activity),closed=state==='closed',box=el('span','f-window is-'+(closed?'closed':'open')),day=limaDate(new Date(closes));
  if(!SPAN.test(activity.time||'')&&closes===Date.parse(`${activity.date}T00:00:00-05:00`)+864e5){box.append(tr('span',closed?'checkinClosedAllDay':'checkinOpenAllDay','f-window-label'));return box;}
  box.append(tr('span',closed?'checkinClosedAt':'checkinOpenUntil','f-window-label'),el('span','f-window-time',limaClock(closes)));if(day!==activity.date)box.append(dateNode(day,'span','short','f-window-day'));
  box.append(tr('span','limaTime','f-window-zone'));return box;
 }
 function hint(key,cls='f-muted'){const p=tr('p',key,cls);p.id='f-hint-'+key;return p;}
 function describe(node,...ids){node.setAttribute('aria-describedby',[...ids,...(node.target==='_blank'?['f-newtab']:[])].join(' '));return node;}
 function newTabNote(){const n=tr('span','newTab','f-sr-only');n.id='f-newtab';return n;}
 const KIND={news:'newsKind',recording:'recording',material:'material'},OPEN={news:'open',recording:'watchRecording',material:'openMaterial'};
 function contentCards(container,items,empty='noNews',heading='h3'){
  container.replaceChildren();if(!items.length){container.append(tr('p',empty,'f-muted f-empty'));return;}
  for(const item of items){
   const card=el('article','f-news-item'),meta=el('p','f-news-meta'),title=source(heading,item.title);
   meta.append(tr('span',KIND[item.kind]||'newsKind','f-chip'));
   if(item.createdAt&&Number.isFinite(Date.parse(item.createdAt)))meta.append(dateNode(limaDate(new Date(item.createdAt)),'span','short','f-news-date'));
   card.append(meta,title,source('p',item.body,'f-news-body'));
   if(item.url){const a=link(OPEN[item.kind]||'open',item.url,'f-text-link');if(item.id){title.id='f-c-'+item.id;describe(a,title.id);}card.append(a);}
   container.append(card);
  }
 }
 const findActivity=(event,id)=>[...event.activities,...(event.legacyActivities||[])].find(activity=>activity.id===id);
 // The heading level follows the host (h4 inside the saved summary's h3 section); the dashboard widget uses the short hint.
 // Badges follow the programme (date, then period and time, then catalogue order), never the order the store returns the attendance in.
 function badges(container,attendance,event,{heading='h3',hint='badgesHint'}={}){container.replaceChildren();container.append(tr(heading,'badges'));if(!attendance.length){container.append(tr('p',hint,'f-muted'));return;}
  const attended=new Set(attendance.map(record=>record.activityId));for(const a of chronological([...event.activities,...(event.legacyActivities||[])].filter(a=>attended.has(a.id))))container.append(source('p','✓ '+a.title,'f-badge'));}
 // Scrolls a horizontal chip row just enough to show the item in full, clear of the right-edge fade (fiiu.css); only the row moves, never the page (the rows sit in sticky bars).
 function revealInRow(row,item){const box=item?.getBoundingClientRect?.(),frame=row?.getBoundingClientRect?.();if(!box||!frame)return;const shift=box.left<frame.left+8?box.left-frame.left-8:box.right>frame.right-36?box.right-frame.right+36:0;if(shift)row.scrollBy?.({left:shift});}
 window.Fiiu={rows,t,el,tr,button,link,source,field,check,api,status,dateNode,rangeNode,limaDate,locale,contentCards,badges,findActivity,chronological,typeOf,countLabel,nextFor,hint,describe,newTabNote,revealInRow,minutesOf,hoursOf,hoursText,hoursLine,checkinCloses,checkinState,checkinActivities,limaClock,windowNode};
 window.nodalI18n?.onChange(refresh);refresh();
})();
