(() => {
 'use strict';
 const rows={
 externalActivities:['Workshop and route interests','Interés en talleres y rutas','Interesse em oficinas e roteiros'],
 externalInterestHint:['Save your interests here, then complete each activity’s Google Form to register with its facilitator. Interest in NODAL does not confirm that registration or attendance.','Guarda aquí tus actividades de interés y completa el Google Form de cada una para inscribirte con su facilitador. El interés en NODAL no confirma esa inscripción ni la asistencia.','Salve seus interesses aqui e preencha o Google Forms de cada atividade para se inscrever com o facilitador. O interesse na NODAL não confirma essa inscrição nem a presença.'],
 externalForm:['Complete the activity form','Completar el formulario de la actividad','Preencher o formulário da atividade'],
 partyHint:['The closing party has separate registration. Check its details with the festival organisers.','La fiesta de cierre tiene inscripción independiente. Consulta los detalles con la organización del festival.','A festa de encerramento tem inscrição independente. Consulte os detalhes com a organização do festival.'],
 accessibilityHint:['Choose any support you need, or explicitly select no additional support.','Selecciona el apoyo que necesitas o indica que no necesitas apoyo adicional.','Selecione o apoio de que precisa ou indique que não precisa de apoio adicional.'],
 accessibilityRequired:['Choose an accessibility answer, including no additional support if appropriate.','Elige una respuesta de accesibilidad, incluyendo no necesito apoyo adicional cuando corresponda.','Escolha uma resposta sobre acessibilidade, incluindo não preciso de apoio adicional quando for o caso.'],
 apply:['Apply','Postular','Candidatar-se'],
 summaryTitle:['Registration overview','Resumen de inscripciones','Resumo das inscrições'],
 summaryHint:['Totals refresh every minute while this page is visible, or when you select Refresh totals. Each person is counted once per day; external interest is separate from attendance.','Los totales se actualizan cada minuto mientras esta página está visible, o al pulsar Actualizar totales. Cada persona cuenta una vez por día; el interés externo es distinto de la asistencia.','Os totais são atualizados a cada minuto enquanto esta página está visível, ou ao selecionar Atualizar totais. Cada pessoa conta uma vez por dia; o interesse externo é diferente da presença.'],
 refreshSummary:['Refresh totals','Actualizar totales','Atualizar totais'],
 totalRegistrations:['Event registrations','Inscripciones al evento','Inscrições no evento'],
 publicOfficials:['Public officials','Funcionarios públicos','Gestores públicos'],
 byDay:['By day','Por día','Por dia'],byActivity:['By activity','Por actividad','Por atividade'],profiles:['Participant profiles','Perfiles de participantes','Perfis dos participantes'],
 participantCount:['People','Personas','Pessoas'],registered:['Registered / applied','Inscripciones / postulaciones','Inscrições / candidaturas'],attended:['Confirmed attendance','Asistencia confirmada','Presença confirmada'],day:['Day','Día','Dia'],activity:['Activity','Actividad','Atividade'],unspecified:['Not provided','No informado','Não informado'],
 activities:['Conference registrations','Inscripciones a conferencias','Inscrições nas conferências'],
 accountChanged:['Your signed-in account changed. Your draft is still here. Reload to continue with the current account.','Tu cuenta ha cambiado. Tu borrador sigue aquí. Recarga para continuar con la cuenta actual.','Sua conta mudou. Seu rascunho continua aqui. Recarregue para continuar com a conta atual.'],
 reloadAccount:['Reload for current account','Recargar para la cuenta actual','Recarregar para a conta atual'],
 reloadSaved:['Reload saved registration','Recargar inscripción guardada','Recarregar inscrição salva'],
 savedRefreshFailed:['Saved, but the latest list could not be loaded. Your changes are safe.','Guardado, pero no se pudo cargar la lista actualizada. Tus cambios están guardados.','Salvo, mas não foi possível carregar a lista atualizada. Suas alterações estão salvas.'],
  spanishContent:['ES · Content in Spanish','ES · Contenido en español','ES · Conteúdo em espanhol'],
  languageHint:['Programme titles and session descriptions are available in Spanish. Navigation and registration follow your selected language.','Los títulos del programa y las descripciones de las sesiones están disponibles en español. La navegación y la inscripción siguen el idioma que elijas.','Os títulos da programação e as descrições das sessões estão disponíveis em espanhol. A navegação e a inscrição seguem o idioma escolhido.'],
  program:['Programme','Programa','Programa'],community:['Community','Comunidad','Comunidade'],resources:['Resources','Recursos','Recursos'],knowledge:['Knowledge','Conocimiento','Conhecimento'],panel:['My console','Mi panel','Meu painel'],
  skip:['Skip to content','Ir al contenido','Ir para o conteúdo'],loading:['Loading…','Cargando…','Carregando…'],retry:['Try again','Reintentar','Tentar novamente'],
  intro:['Connect with the people shaping our cities. Choose your conference blocks and manage your FIIU participation in NODAL.','Conecta con quienes transforman nuestras ciudades. Elige tus bloques de conferencias y gestiona tu participación en FIIU desde NODAL.','Conecte-se com quem transforma nossas cidades. Escolha seus blocos de conferências e gerencie sua participação no FIIU pela NODAL.'],
  dates:['20–25 October 2026','20–25 de octubre de 2026','20–25 de outubro de 2026'],register:['Register','Inscríbete','Inscreva-se'],website:['Festival website','Web del festival','Site do festival'],officialProgram:['View the live programme','Ver el programa en vivo','Ver a programação ao vivo'],
  programmeTitle:['Make room for the city','Haz espacio para la ciudad','Abra espaço para a cidade'],programmeHint:['Times are in Lima. The programme may change; admission is subject to each venue’s capacity.','Horarios de Lima. El programa está sujeto a cambios y el ingreso depende del aforo de cada espacio.','Horários de Lima. A programação pode mudar e a entrada depende da capacidade de cada espaço.'],
  morning:['Morning block','Bloque de mañana','Bloco da manhã'],evening:['Evening block','Bloque de noche','Bloco da noite'],lab:['Public-officials laboratory','Laboratorio para funcionarios','Laboratório para gestores públicos'],workshop:['Workshops','Talleres','Oficinas'],route:['Urban routes','Rutas urbanas','Roteiros urbanos'],venuePending:['Venue to be confirmed','Lugar por confirmar','Local a confirmar'],timePending:['Time to be confirmed','Horario por confirmar','Horário a confirmar'],
  external:['Separate registration','Inscripción independiente','Inscrição separada'],externalHint:['Workshops, urban routes and the closing party have separate registration. Visit the festival website for details.','Los talleres, las rutas urbanas y la fiesta de cierre tienen inscripción independiente. Consulta los detalles en la web del festival.','Oficinas, roteiros urbanos e festa de encerramento têm inscrição separada. Confira os detalhes no site do festival.'],party:['Closing party','Fiesta de cierre','Festa de encerramento'],
  registration:['Your FIIU registration','Tu inscripción al FIIU','Sua inscrição no FIIU'],signinHint:['Use your NODAL account to register. Your registration stays in your console, where you can review and update it.','Usa tu cuenta de NODAL para inscribirte. Tu inscripción queda en Mi panel para revisarla y actualizarla.','Use sua conta NODAL para se inscrever. Sua inscrição fica no painel, onde você pode consultar e atualizar.'],signin:['Sign in or create an account','Inicia sesión o crea tu cuenta','Entre ou crie sua conta'],
  personal:['About you','Tus datos','Seus dados'],choices:['Choose your activities','Elige tus actividades','Escolha suas atividades'],questionnaire:['A few questions','Algunas preguntas','Algumas perguntas'],privateHint:['These answers are private to you and the organising team. They are not published on your NODAL profile.','Estas respuestas son privadas para ti y el equipo organizador. No se publican en tu perfil de NODAL.','Estas respostas são privadas para você e a equipe organizadora. Não são publicadas no seu perfil NODAL.'],
  firstName:['First name','Nombres','Nome'],lastName:['Last name','Apellidos','Sobrenome'],email:['Account email','Correo de tu cuenta','E-mail da conta'],country:['Country of origin','País de origen','País de origem'],city:['City of residence','Ciudad de residencia','Cidade de residência'],profile:['Your main profile','Tu perfil principal','Seu perfil principal'],
  choose:['Select an option','Selecciona una opción','Selecione uma opção'],student:['Student','Estudiante','Estudante'],academic:['Academic','Académico/a','Acadêmico/a'],researcher:['Researcher','Investigador/a','Pesquisador/a'],professional:['Private-sector professional','Profesional del sector privado','Profissional do setor privado'],entrepreneur:['Entrepreneur','Emprendedor/a','Empreendedor/a'],activist:['Activist / community leader','Activista / líder comunitario','Ativista / liderança comunitária'],organization:['Organisation / collective member','Miembro de organización / colectivo','Membro de organização / coletivo'],public_official:['Public official','Funcionario/a público/a','Gestor/a público/a'],other:['Other','Otro','Outro'],
  publicOfficial:['Are you currently a public official?','¿Actualmente eres funcionario/a público/a?','Você é atualmente gestor/a público/a?'],yes:['Yes','Sí','Sim'],no:['No','No','Não'],
  applyLab:['Apply for the 20 October laboratory','Postular al laboratorio del 20 de octubre','Candidatar-se ao laboratório de 20 de outubro'],labHint:['For public officials from local governments. Applications are reviewed by the organisers; applying does not confirm admission. Supported by CAF, Fundación FEMSA and UNACEM.','Dirigido a funcionarios de gobiernos locales. El equipo revisará las postulaciones; postular no confirma el ingreso. Promovido junto con CAF, Fundación FEMSA y UNACEM.','Para gestores de governos locais. A equipe analisa as candidaturas; candidatar-se não confirma a admissão. Promovido com CAF, Fundación FEMSA e UNACEM.'],institution:['Institution you represent','Institución a la que representas','Instituição que representa'],position:['Department and role','Área y cargo profesional','Área e cargo profissional'],
  nationalId:['National ID','Cédula o DNI','Documento de identidade'],gender:['Gender','Género','Gênero'],female:['Female','Femenino','Feminino'],male:['Male','Masculino','Masculino'],prefer_not:['Prefer not to say','Prefiero no responder','Prefiro não responder'],age:['Age','Edad','Idade'],accessibility:['Accessibility support','Apoyo de accesibilidad','Apoio de acessibilidade'],none:['No additional support','No necesito apoyo adicional','Não preciso de apoio adicional'],mobility:['Mobility support','Apoyo en movilidad','Apoio de mobilidade'],visual:['Visual adaptations','Adaptaciones visuales','Adaptações visuais'],hearing:['Hearing adaptations','Adaptaciones auditivas','Adaptações auditivas'],communication:['Communication or cognitive support','Apoyo de comunicación o cognitivo','Apoio de comunicação ou cognitivo'],accessibilityOther:['Describe the support you need','Describe el apoyo que necesitas','Descreva o apoio de que precisa'],
  motivation:['Main motivation','Motivación principal','Motivação principal'],learn:['Learn about citizenship and urbanism','Aprender sobre ciudadanía y urbanismo','Aprender sobre cidadania e urbanismo'],career:['Professional development','Desarrollo profesional','Desenvolvimento profissional'],network:['Meet and connect with people','Conocer y conectar con personas','Conhecer e conectar pessoas'],explore:['Discover the city','Descubrir la ciudad','Conhecer a cidade'],motivationOther:['Describe your other motivation','Describe tu otra motivación','Descreva sua outra motivação'],previousAttendance:['Have you attended FIIU before?','¿Has participado en ediciones anteriores?','Já participou de outras edições?'],all:['Every edition','Todas las ediciones','Todas as edições'],some:['Some editions','Algunas ediciones','Algumas edições'],
  privacyAccepted:['I agree to share these answers with the FIIU organising team to manage my participation and any accessibility support I request.','Acepto compartir estas respuestas con el equipo organizador del FIIU para gestionar mi participación y el apoyo de accesibilidad que solicite.','Concordo em compartilhar estas respostas com a equipe organizadora do FIIU para gerenciar minha participação e o apoio de acessibilidade solicitado.'],privacy:['Read the privacy policy','Leer la política de privacidad','Ler a política de privacidade'],save:['Save my registration','Guardar mi inscripción','Salvar minha inscrição'],saving:['Saving…','Guardando…','Salvando…'],saved:['Your registration is saved','Tu inscripción está guardada','Sua inscrição está salva'],savedHint:['This is your saved registration. Admission remains subject to venue capacity.','Esta es tu inscripción guardada. El ingreso sigue sujeto al aforo de cada espacio.','Esta é sua inscrição salva. A entrada continua sujeita à capacidade de cada espaço.'],edit:['Edit registration','Editar inscripción','Editar inscrição'],cancel:['Cancel registration','Cancelar inscripción','Cancelar inscrição'],cancelConfirm:['Cancel your registration and remove its answers and attendance badges?','¿Cancelar tu inscripción y eliminar sus respuestas e insignias de asistencia?','Cancelar sua inscrição e remover suas respostas e insígnias de presença?'],cancelled:['Your registration was cancelled.','Tu inscripción fue cancelada.','Sua inscrição foi cancelada.'],
  pending:['Laboratory application pending review','Postulación al laboratorio en revisión','Candidatura ao laboratório em análise'],accepted:['Laboratory application accepted','Postulación al laboratorio aceptada','Candidatura ao laboratório aceita'],declined:['Laboratory application not selected','Postulación al laboratorio no seleccionada','Candidatura ao laboratório não selecionada'],badges:['Participation badges','Insignias de participación','Insígnias de participação'],badgesHint:['Badges appear after the team confirms your attendance. Registration alone does not earn a badge.','Las insignias aparecen cuando el equipo confirma tu asistencia. La inscripción por sí sola no otorga insignias.','As insígnias aparecem depois que a equipe confirma sua presença. A inscrição não gera uma insígnia.'],
  adminInvalid:['Check the required fields and use HTTPS for links.','Revisa los campos obligatorios y utiliza HTTPS en los enlaces.','Revise os campos obrigatórios e use HTTPS nos links.'],editorConflict:['Another organizer changed this information. Reload to review the latest version before saving again.','Otro organizador cambió esta información. Recarga para revisar la versión actual antes de guardar de nuevo.','Outro organizador alterou estas informações. Recarregue para conferir a versão atual antes de salvar novamente.'],
  error:['We could not complete the request. Your answers are still here. Try again.','No pudimos completar la solicitud. Tus respuestas siguen aquí. Intenta de nuevo.','Não foi possível concluir a solicitação. Suas respostas continuam aqui. Tente novamente.'],invalid:['Review the required fields and choose a conference, a workshop or route interest, or apply for the laboratory.','Revisa los campos obligatorios y elige una conferencia, un taller o ruta de interés, o postula al laboratorio.','Revise os campos obrigatórios e escolha uma conferência, uma oficina ou roteiro de interesse, ou candidate-se ao laboratório.'],conflict:['This registration changed in another window. Your draft is still here. Review the saved version before replacing it.','Esta inscripción cambió en otra ventana. Tu borrador sigue aquí. Revisa la versión guardada antes de reemplazarla.','Esta inscrição mudou em outra janela. Seu rascunho continua aqui. Revise a versão salva antes de substituí-la.'],viewSaved:['Review saved registration','Revisar inscripción guardada','Revisar inscrição salva'],useLatest:['Use the current version for my next save','Usar la versión actual para mi próximo guardado','Usar a versão atual no próximo salvamento'],closed:['Registration is currently closed.','La inscripción está cerrada por ahora.','As inscrições estão fechadas no momento.'],unauthorized:['Sign in again to continue. Your draft stays here.','Vuelve a iniciar sesión para continuar. Tu borrador queda aquí.','Entre novamente para continuar. Seu rascunho permanece aqui.'],forbidden:['This action is not available for your account.','Esta acción no está disponible para tu cuenta.','Esta ação não está disponível para sua conta.'],rate:['Please wait a minute before trying again.','Espera un minuto antes de volver a intentarlo.','Aguarde um minuto antes de tentar novamente.'],
  news:['Festival news','Noticias del festival','Notícias do festival'],noNews:['Festival updates will appear here when the team publishes them.','Las novedades aparecerán aquí cuando el equipo las publique.','As novidades aparecerão aqui quando a equipe publicar.'],materials:['Recordings and materials','Grabaciones y materiales','Gravações e materiais'],noMaterials:['Recordings and materials will be shared here during and after the festival.','Las grabaciones y los materiales se compartirán aquí durante y después del festival.','Gravações e materiais serão compartilhados aqui durante e depois do festival.'],open:['Open link','Abrir enlace','Abrir link'],recording:['Recording','Grabación','Gravação'],material:['Material','Material','Material'],newsKind:['News','Noticia','Notícia'],admin:['Organiser dashboard','Panel de organización','Painel da organização'],participants:['Participants','Participantes','Participantes'],export:['Download registrations CSV','Descargar inscripciones CSV','Baixar inscrições CSV'],loadMore:['Load more','Cargar más','Carregar mais'],details:['View details','Ver detalles','Ver detalhes'],noParticipants:['No registrations yet.','Aún no hay inscripciones.','Ainda não há inscrições.'],review:['Laboratory review','Revisión del laboratorio','Análise do laboratório'],reviewPending:['Pending','Pendiente','Pendente'],reviewAccepted:['Accepted','Aceptada','Aceita'],reviewDeclined:['Not selected','No seleccionada','Não selecionada'],saveReview:['Save review','Guardar revisión','Salvar análise'],attendance:['Confirm attendance','Confirmar asistencia','Confirmar presença'],attendanceHint:['Mark only attendance verified by the organising team.','Marca solo la asistencia verificada por el equipo organizador.','Marque apenas a presença verificada pela equipe organizadora.'],
  settings:['Registration and links','Inscripción y enlaces','Inscrição e links'],registrationOpen:['Accept registrations','Aceptar inscripciones','Aceitar inscrições'],programUrl:['Official programme URL','Enlace del programa oficial','Link da programação oficial'],workshopsUrl:['Workshop registration URL','Enlace de inscripción a talleres','Link de inscrição nas oficinas'],routesUrl:['Urban route registration URL','Enlace de inscripción a rutas','Link de inscrição nos roteiros'],partyUrl:['Closing party registration URL','Enlace de inscripción a la fiesta','Link de inscrição na festa'],saveSettings:['Save settings','Guardar configuración','Salvar configurações'],changesSaved:['Changes saved.','Cambios guardados.','Alterações salvas.'],content:['News and materials','Noticias y materiales','Notícias e materiais'],newContent:['New publication','Nueva publicación','Nova publicação'],title:['Title','Título','Título'],body:['Text','Texto','Texto'],kind:['Type','Tipo','Tipo'],url:['HTTPS link','Enlace HTTPS','Link HTTPS'],activityId:['Related activity','Actividad relacionada','Atividade relacionada'],status:['Publication status','Estado de publicación','Status de publicação'],draft:['Draft','Borrador','Rascunho'],published:['Published','Publicado','Publicado'],archived:['Archived','Archivado','Arquivado'],saveContent:['Save publication','Guardar publicación','Salvar publicação'],editContent:['Edit publication','Editar publicación','Editar publicação'],back:['Back','Volver','Voltar'],
  factWhen:['When','Cuándo','Quando'],factProgramme:['Programme','Programa','Programação'],factRegistration:['Registration','Inscripción','Inscrição'],
  registrationOpenNow:['Registration open','Inscripciones abiertas','Inscrições abertas'],registrationClosedNow:['Registration closed','Inscripciones cerradas','Inscrições encerradas'],
  conferenceOne:['conference block','bloque de conferencias','bloco de conferências'],conferenceMany:['conference blocks','bloques de conferencias','blocos de conferências'],
  workshopOne:['workshop','taller','oficina'],workshopMany:['workshops','talleres','oficinas'],
  routeOne:['urban route','ruta urbana','roteiro urbano'],routeMany:['urban routes','rutas urbanas','roteiros urbanos'],
  labOne:['laboratory for public officials','laboratorio para funcionarios','laboratório para gestores públicos'],
  interestOne:['interest','interés','interesse'],interestMany:['interests','intereses','interesses'],
  sessionOne:['session','sesión','sessão'],sessions:['sessions','sesiones','sessões'],
  viewRegistration:['View my registration','Ver mi inscripción','Ver minha inscrição'],
  statusRegistered:['Registered','Inscrito/a','Inscrito/a'],statusNotRegistered:['Not registered yet','Aún sin inscripción','Ainda sem inscrição'],
  actionNeeded:['Action needed','Acción necesaria','Ação necessária'],
  datesMonth:['October 2026','Octubre 2026','Outubro 2026'],nextForYou:['Next for you','Lo próximo para ti','Próximo para você'],latestUpdate:['Latest update','Última novedad','Última novidade'],
  pendingShort:['Lab: in review','Laboratorio: en revisión','Laboratório: em análise'],acceptedShort:['Lab: accepted','Laboratorio: aceptada','Laboratório: aceita'],declinedShort:['Lab: not selected','Laboratorio: no seleccionada','Laboratório: não selecionada'],
  pendingHint:['The organising team is reviewing applications. The decision will appear here.','El equipo organizador está revisando las postulaciones. La decisión aparecerá aquí.','A equipe organizadora está analisando as candidaturas. A decisão aparecerá aqui.'],
  acceptedHint:['Your place in the 20 October laboratory is confirmed.','Tu lugar en el laboratorio del 20 de octubre está confirmado.','Sua vaga no laboratório de 20 de outubro está confirmada.'],
  declinedHint:['Your application was not selected this time. Your other registrations are unchanged.','Tu postulación no fue seleccionada esta vez. Tus demás inscripciones no cambian.','Sua candidatura não foi selecionada desta vez. Suas demais inscrições continuam iguais.'],
  dayNav:['Festival days','Días del festival','Dias do festival'],
  workshopType:['Workshop','Taller','Oficina'],routeType:['Urban route','Ruta urbana','Roteiro urbano'],
  addToRegistration:['Add to my registration','Añadir a mi inscripción','Adicionar à minha inscrição'],saveInterest:['Save as interest','Guardar como interés','Salvar como interesse'],
  interestChip:['Interest saved','Interés guardado','Interesse salvo'],activityForm:['Activity form','Formulario de la actividad','Formulário da atividade'],
  externalFormNext:['Next step: complete the activity form','Siguiente paso: completa el formulario de la actividad','Próximo passo: preencha o formulário da atividade'],
  newTab:['(opens in a new tab)','(se abre en una pestaña nueva)','(abre em uma nova aba)'],
  partyRegister:['Register for the closing party','Inscríbete en la fiesta de cierre','Inscreva-se na festa de encerramento'],partyDetails:['Closing party details','Detalles de la fiesta de cierre','Detalhes da festa de encerramento'],
  formIntro:['Takes about 5 minutes. Fields marked * are required.','Toma unos 5 minutos. Los campos marcados con * son obligatorios.','Leva cerca de 5 minutos. Os campos marcados com * são obrigatórios.'],
  formDuration:['Registration takes about 5 minutes.','La inscripción toma unos 5 minutos.','A inscrição leva cerca de 5 minutos.'],
  canConferences:['Choose your conference blocks','Elige tus bloques de conferencias','Escolha seus blocos de conferências'],
  canLab:['Apply for the laboratory for public officials','Postula al laboratorio para funcionarios','Candidate-se ao laboratório para gestores públicos'],
  canInterests:['Save workshop and urban route interests','Guarda talleres y rutas urbanas de interés','Salve oficinas e roteiros de interesse'],
  stepsLabel:['Registration steps','Pasos de la inscripción','Etapas da inscrição'],consentStep:['Accessibility and consent','Accesibilidad y consentimiento','Acessibilidade e consentimento'],
  // Short step names for the sticky step bar; the fieldset legends keep the full wording.
  stepChoices:['Activities','Actividades','Atividades'],stepQuestions:['Questions','Preguntas','Perguntas'],stepConsent:['Consent','Consentimiento','Consentimento'],
  choiceAdded:['Selected · save to confirm','Seleccionado · guarda para confirmar','Selecionado · salve para confirmar'],
  requiredGroup:[' (required)',' (obligatorio)',' (obrigatório)'],
  choicesHint:['Choose at least one conference block, workshop or route interest, or the laboratory. Times are in Lima.','Elige al menos un bloque de conferencias, un taller o ruta de interés, o el laboratorio. Horarios de Lima.','Escolha pelo menos um bloco de conferências, uma oficina ou roteiro de interesse, ou o laboratório. Horários de Lima.'],
  labQuestionHint:['Public officials who answer Yes can apply for the 20 October laboratory.','Si respondes Sí, podrás postular al laboratorio del 20 de octubre.','Se responder Sim, você poderá se candidatar ao laboratório de 20 de outubro.'],
  labApplied:['lab application','postulación al laboratorio','candidatura ao laboratório'],selectionNone:['Nothing selected yet','Aún no has elegido nada','Nada selecionado ainda'],
  backToSaved:['Back to my registration','Volver a mi inscripción','Voltar para minha inscrição'],
  requiredField:['Answer this question to continue.','Responde esta pregunta para continuar.','Responda a esta pergunta para continuar.'],
  privacyRequired:['Confirm this to save your registration.','Confirma esta casilla para guardar tu inscripción.','Confirme esta opção para salvar sua inscrição.'],
  invalidAge:['Enter your age as a whole number between 1 and 120.','Escribe tu edad como un número entero entre 1 y 120.','Informe sua idade como um número inteiro entre 1 e 120.'],
  chooseActivity:['Choose a conference block, save a workshop or route interest, or apply for the laboratory.','Elige un bloque de conferencias, guarda un taller o ruta de interés, o postula al laboratorio.','Escolha um bloco de conferências, salve uma oficina ou roteiro de interesse, ou candidate-se ao laboratório.'],
  reviewErrors:['Some answers need attention. The first one is highlighted.','Algunas respuestas necesitan revisión. La primera está resaltada.','Algumas respostas precisam de revisão. A primeira está destacada.'],
  answersNeedAttention:['Some answers need attention','Algunas respuestas necesitan revisión','Algumas respostas precisam de revisão'],
  stepDone:['completed','completado','concluída'],
  latestReplace:['Your next save will replace the saved version with this draft.','Al guardar, este borrador reemplazará la versión guardada.','Ao salvar, este rascunho substituirá a versão salva.'],
  latestCreate:['The saved registration no longer exists. Your next save will register you again with this draft.','La inscripción guardada ya no existe. Al guardar, te inscribirás de nuevo con este borrador.','A inscrição salva não existe mais. Ao salvar, você fará uma nova inscrição com este rascunho.'],
  labType:['Laboratory for public officials · by application','Laboratorio para funcionarios · con postulación','Laboratório para gestores públicos · com candidatura'],
  loadError:['We could not load the festival information. Try again.','No pudimos cargar la información del festival. Intenta de nuevo.','Não foi possível carregar as informações do festival. Tente novamente.'],
  hubMaterials:['Recordings and materials will appear on the FIIU page as the team shares them.','Las grabaciones y los materiales aparecerán en la página del FIIU cuando el equipo los comparta.','Gravações e materiais aparecerão na página do FIIU quando a equipe compartilhar.'],
  incompleteNotice:['Action needed: some required answers are missing. Edit your registration to complete them.','Acción necesaria: faltan algunas respuestas obligatorias. Edita tu inscripción para completarlas.','Ação necessária: faltam algumas respostas obrigatórias. Edite sua inscrição para completá-las.'],
  incompleteClosedNotice:['Action needed: some required answers are missing. Registration is closed, so write to fiiu@ocupatucalle.com to complete them.','Acción necesaria: faltan algunas respuestas obligatorias. La inscripción está cerrada: escribe a fiiu@ocupatucalle.com para completarlas.','Ação necessária: faltam algumas respostas obrigatórias. As inscrições estão encerradas: escreva para fiiu@ocupatucalle.com para completá-las.'],
  badgesHintShort:['Badges appear once your attendance is confirmed.','Las insignias aparecen cuando se confirma tu asistencia.','As insígnias aparecem quando sua presença é confirmada.'],
  myPlan:['Your programme','Tu programa','Sua programação'],
  allNews:['All festival news','Todas las noticias del festival','Todas as notícias do festival'],
  watchRecording:['Watch recording','Ver grabación','Assistir à gravação'],openMaterial:['Open material','Abrir material','Abrir material'],
  // Organiser dashboard and member dashboard widget.
  navOverview:['Overview','Resumen','Visão geral'],sectionNav:['Sections','Secciones','Seções'],viewPublic:['View public page','Ver página pública','Ver página pública'],
  exportNote:['Contains private answers (ID, accessibility). Store it securely and delete it after the festival.','Contiene respuestas privadas (documento, accesibilidad). Guárdalo de forma segura y elimínalo después del festival.','Contém respostas privadas (documento, acessibilidade). Guarde com segurança e exclua após o festival.'],
  labApplications:['Laboratory applications','Postulaciones al laboratorio','Candidaturas ao laboratório'],reviewPendingAction:['Review pending applications','Revisar postulaciones pendientes','Analisar candidaturas pendentes'],
  todayTitle:['Today at the festival','Hoy en el festival','Hoje no festival'],updatedAt:['Updated','Actualizado','Atualizado'],
  peopleWithPlans:['People with plans','Personas con planes','Pessoas com planos'],
  byDayHint:['Each person counts once per day, whether they registered for a conference, applied for the laboratory or saved a workshop or route interest.','Cada persona cuenta una vez por día, ya sea por inscribirse en una conferencia, postular al laboratorio o guardar un taller o ruta de interés.','Cada pessoa conta uma vez por dia, seja por se inscrever em uma conferência, candidatar-se ao laboratório ou salvar uma oficina ou roteiro de interesse.'],
  conferencesAndLab:['Conferences and laboratory','Conferencias y laboratorio','Conferências e laboratório'],interested:['Interested','Interesados','Interessados'],
  registeredShort:['Reg.','Inscr.','Inscr.'],attendedShort:['Att.','Asist.','Pres.'],interestedShort:['Interest','Interés','Interesse'],peopleWithPlansShort:['People','Personas','Pessoas'],
  searchParticipants:['Search by name or email','Buscar por nombre o correo','Buscar por nome ou e-mail'],filterLabel:['Filter participants','Filtrar participantes','Filtrar participantes'],
  filterAll:['All','Todos','Todos'],filterLabPending:['Lab: pending','Laboratorio: pendientes','Laboratório: pendentes'],filterLabAccepted:['Lab: accepted','Laboratorio: aceptadas','Laboratório: aceitas'],
  participantShownOne:['participant shown','participante mostrado','participante exibido'],participantShownMany:['participants shown','participantes mostrados','participantes exibidos'],
  showingLoaded:['Showing people loaded so far. Load more to search everyone.','Se muestran las personas cargadas hasta ahora. Carga más para buscar entre todas.','Mostrando as pessoas carregadas até agora. Carregue mais para buscar entre todas.'],
  noMatches:['No participants match this search or filter.','Ningún participante coincide con esta búsqueda o filtro.','Nenhum participante corresponde a esta busca ou filtro.'],showAll:['Show everyone','Mostrar a todas las personas','Mostrar todas as pessoas'],
  autoRefresh:['Refresh every minute','Actualizar cada minuto','Atualizar a cada minuto'],
  selectParticipant:['Select a participant to see their answers, lab review and attendance.','Selecciona un participante para ver sus respuestas, la revisión del laboratorio y la asistencia.','Selecione um participante para ver suas respostas, a análise do laboratório e a presença.'],
  backToList:['Back to the list','Volver a la lista','Voltar para a lista'],allAnswers:['All answers','Todas las respuestas','Todas as respostas'],
  profileAdmin:['Profile','Perfil','Perfil'],publicOfficialAdmin:['Public official','Funcionario/a público/a','Gestor/a público/a'],applyLabAdmin:['Laboratory application','Postulación al laboratorio','Candidatura ao laboratório'],institutionAdmin:['Institution','Institución','Instituição'],
  previousAttendanceAdmin:['Previous editions','Ediciones anteriores','Edições anteriores'],accessibilityOtherAdmin:['Support details','Detalle del apoyo','Detalhes do apoio'],motivationOtherAdmin:['Other motivation','Otra motivación','Outra motivação'],
  externalInterestAdminHint:['Interest only. Facilitators register people through their own Google Form.','Solo interés. Cada facilitador inscribe a las personas con su propio Google Form.','Apenas interesse. Cada facilitador inscreve as pessoas pelo próprio Google Forms.'],
  showId:['Show','Mostrar','Mostrar'],hideId:['Hide','Ocultar','Ocultar'],
  otherActivities:['Other workshops and routes this day','Otros talleres y rutas de este día','Outras oficinas e roteiros deste dia'],
  attendanceSaved:['Saved','Guardado','Salvo'],reloadLatest:['Reload the latest version','Recargar la versión actual','Recarregar a versão atual'],
  closeConfirm:['Close registration? New people will not be able to register; saved registrations stay.','¿Cerrar la inscripción? Nadie nuevo podrá inscribirse; las inscripciones guardadas se mantienen.','Encerrar as inscrições? Novas pessoas não poderão se inscrever; as inscrições salvas continuam.'],
  registrationOpenHint:['When closed, new people cannot register. Saved registrations stay.','Cuando está cerrada, nadie nuevo puede inscribirse. Las inscripciones guardadas se mantienen.','Quando encerrada, novas pessoas não podem se inscrever. As inscrições salvas continuam.'],
  publicLinks:['Links shown on the public page','Enlaces que se muestran en la página pública','Links exibidos na página pública'],
  cancelEdit:['Cancel editing','Cancelar edición','Cancelar edição'],
  pendingReviewOne:['application pending review','postulación pendiente de revisión','candidatura pendente de análise'],pendingReviewMany:['applications pending review','postulaciones pendientes de revisión','candidaturas pendentes de análise'],
  communityTitle:['A community that meets','Una comunidad que se encuentra','Uma comunidade que se encontra'],communityIntro:['Meet people, share experiences and build connections through the city.','Encuentra personas, comparte experiencias y crea vínculos a través de la ciudad.','Encontre pessoas, compartilhe experiências e crie conexões pela cidade.'],chelas:['Chelas urbanas','Chelas urbanas','Chelas urbanas'],chelasHint:['Explore local learning circles and meetups. To propose an urban meetup, contact the NODAL team.','Explora círculos de aprendizaje y encuentros locales. Para proponer una chela urbana, contacta al equipo NODAL.','Explore círculos de aprendizagem e encontros locais. Para propor um encontro urbano, fale com a equipe NODAL.'],organize:['Propose an urban meetup','Proponer una chela urbana','Propor um encontro urbano'],events:['Community events','Eventos de la comunidad','Eventos da comunidade'],circles:['Explore learning circles','Explorar círculos de aprendizaje','Explorar círculos de aprendizagem'],people:['Meet the network','Conoce la red','Conheça a rede'],resourcesTitle:['Ideas and opportunities to put into practice','Ideas y oportunidades para llevar a la práctica','Ideias e oportunidades para colocar em prática'],opportunities:['Explore opportunities','Explorar oportunidades','Explorar oportunidades'],knowledgeTitle:['Knowledge we build together','Conocimiento que construimos juntos','Conhecimento que construímos juntos'],courses:['Courses','Cursos','Cursos'],coursesHint:['Learn with the community, access sessions and share your work.','Aprende con la comunidad, accede a sesiones y comparte tu trabajo.','Aprenda com a comunidade, acesse sessões e compartilhe seu trabalho.'],masterclasses:['Masterclasses and resources','Masterclasses y recursos','Masterclasses e recursos'],masterclassesHint:['Explore published resources, case studies and shared knowledge.','Explora recursos publicados, casos de estudio y conocimiento compartido.','Explore recursos publicados, estudos de caso e conhecimento compartilhado.'],browseResources:['Browse resources','Explorar recursos','Explorar recursos'],
 };
 const lang=()=>window.nodalI18n?.lang||document.documentElement.lang||'en';
 const t=key=>rows[key]?.[Math.max(0,['en','es','pt'].indexOf(lang()))]||key;
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 const tr=(tag,key,cls)=>{const n=el(tag,cls,t(key));n.dataset.fiiuText=key;return n;};
 const button=(key,fn,cls='f-button')=>{const b=tr('button',key,cls);b.type='button';if(fn)b.addEventListener('click',fn);return b;};
 const link=(key,href,cls='f-button secondary')=>{const a=tr('a',key,cls);a.href=href;if(/^https:\/\//.test(href)){a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-describedby','f-newtab');}return a;};
 const source=(tag,text,cls)=>{const n=el(tag,cls,text);n.lang='es';n.translate=true;return n;};
 function field(key,{value='',type='text',required=false,options,max=200}={}){
  const wrap=el('label','f-field'),label=tr('span',key),star=el('span','f-required',' *'),input=el(options?'select':type==='textarea'?'textarea':'input');
  input.name=key;input.id='f-'+key;if(!options&&type!=='textarea')input.type=type;
  if(options){const blank=tr('option','choose');blank.value='';input.append(blank);for(const v of options){const opt=tr('option',v);opt.value=v;input.append(opt);}}
  input.value=value??'';if(!options)input.maxLength=max;star.setAttribute('aria-hidden','true');wrap.append(label,star,input);
  const setRequired=on=>{input.required=on;star.hidden=!on;};setRequired(required);
  return {wrap,input,setRequired};
 }
 function check(key,name,value,checked=false){const wrap=el('label','f-check'),input=el('input');input.type='checkbox';input.name=name;input.value=value;input.checked=checked;wrap.append(input,tr('span',key));return{wrap,input};}
 async function api(path,body,method){
  let response,data;
  try{response=await fetch(path,{...(body===undefined?{}:{method:method||'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),signal:AbortSignal.timeout(20000)});
   try{data=await response.json();}catch(error){if(response.ok)throw error;data={};}
  }
  catch{throw Object.assign(Error(t('error')),{key:'error'});}
  if(!response.ok){const key=response.status===409&&data?.error==='account changed; reload before continuing'?'accountChanged':path.startsWith('/api/admin/')&&response.status===400?'adminInvalid':path.startsWith('/api/admin/')&&response.status===409?'editorConflict':response.status===403&&data?.error==='registration is closed'?'closed':({400:'invalid',401:'unauthorized',403:'forbidden',409:'conflict',429:'rate'})[response.status]||'error';throw Object.assign(Error(t(key)),{key,status:response.status});}
  if(!data||typeof data!=='object'||Array.isArray(data))throw Object.assign(Error(t('error')),{key:'error'});
  if(path==='/api/fiiu/registration'){
   const r=data.registration;
   if(body===undefined&&(!data.user?.id||typeof data.user.email!=='string'||!Array.isArray(data.attendance)||(r!==null&&(!r?.id||!Number.isSafeInteger(r.version)||r.version<1||!r.answers||!Array.isArray(r.answers.activities)))))throw Object.assign(Error(t('error')),{key:'error'});
   if(method==='PUT'&&(!r||typeof r.id!=='string'||!r.id||r.version!==body.version+1||!r.answers||!Array.isArray(r.answers.activities)||(body.registrationId&&r.id!==body.registrationId)||(body.expectedUserId&&r.userId!==body.expectedUserId)))throw Object.assign(Error(t('error')),{key:'error'});
   if(method==='PUT'&&Array.isArray(body.externalActivities)&&(!Array.isArray(r.answers.externalActivities)||JSON.stringify([...new Set(body.externalActivities)].sort())!==JSON.stringify([...new Set(r.answers.externalActivities)].sort())))throw Object.assign(Error(t('error')),{key:'error'});
   if(method==='DELETE'&&data.ok!==true)throw Object.assign(Error(t('error')),{key:'error'});
  }
  return data;
 }
 function status(node,error){node.textContent=t(error?.key||error||'');node.classList.toggle('is-error',error instanceof Error);node.dataset.fiiuText=error?.key||error||'';}
 const LOCALES={en:'en-GB',es:'es-PE',pt:'pt-BR'},DATE_STYLES={long:{weekday:'long',day:'numeric',month:'long'},short:{weekday:'short',day:'numeric',month:'short'},weekday:{weekday:'short'}};
 const locale=()=>LOCALES[lang()]||'en-GB';
 const cap=text=>text?text.charAt(0).toLocaleUpperCase(locale())+text.slice(1):text;
 const limaNoon=value=>new Date(value+'T12:00:00-05:00');
 const date=(value,style='long')=>cap(new Intl.DateTimeFormat(locale(),{...(DATE_STYLES[style]||DATE_STYLES.long),timeZone:'America/Lima'}).format(limaNoon(value)));
 function dateRange(start,end){const f=new Intl.DateTimeFormat(locale(),{day:'numeric',month:'long',year:'numeric',timeZone:'America/Lima'}),a=limaNoon(start),b=limaNoon(end);return f.formatRange?f.formatRange(a,b):f.format(a)+' – '+f.format(b);}
 const limaDate=(value=new Date())=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'America/Lima'}).format(value);
 function refresh(){
  document.querySelectorAll('[data-fiiu-text]').forEach(n=>{n.textContent=t(n.dataset.fiiuText);});
  document.querySelectorAll('[data-fiiu-date]').forEach(n=>{n.textContent=date(n.dataset.fiiuDate,n.dataset.fiiuDateStyle);});
  document.querySelectorAll('[data-fiiu-range]').forEach(n=>{const [a,b]=n.dataset.fiiuRange.split('/');n.textContent=dateRange(a,b);});
 }
 function dateNode(value,tag='p',style='long',cls='f-date'){const n=el(tag,cls,date(value,style));n.dataset.fiiuDate=value;if(style!=='long')n.dataset.fiiuDateStyle=style;return n;}
 function rangeNode(start,end,tag='span',cls='f-range'){const n=el(tag,cls,dateRange(start,end));n.dataset.fiiuRange=start+'/'+end;return n;}
 const PERIODS=['lab','morning','evening','workshop','route'];
 const rank=activity=>{const i=PERIODS.indexOf(activity.period);return i<0?PERIODS.length:i;};
 // Date, then period, then time; Array#sort is stable, so catalog order breaks the remaining ties.
 const chronological=list=>[...list].sort((a,b)=>a.date.localeCompare(b.date)||rank(a)-rank(b)||(a.time||'').localeCompare(b.time||''));
 const typeOf=activity=>activity.registration==='application'?'lab':activity.registration==='general'?'conference':activity.period==='route'?'route':'workshop';
 // The trailing space keeps copied or read-out text as "5 workshops"; in the flex layout it collapses and the gap spaces the parts.
 function countLabel(n,one,many,cls='f-count'){const box=el('span',cls);box.append(el('b','',new Intl.NumberFormat(locale()).format(n)+' '),tr('span',n===1?one:many));return box;}
 function nextFor(registration,event,today=limaDate()){
  const answers=registration?.answers;if(!answers)return null;
  const ids=new Set([...(answers.activities||[]),...(registration.labStatus==='accepted'?event.activities.filter(a=>a.registration==='application').map(a=>a.id):[])]);
  return chronological(event.activities.filter(a=>ids.has(a.id)&&a.date>=today))[0]||null;
 }
 function hint(key,cls='f-muted'){const p=tr('p',key,cls);p.id='f-hint-'+key;return p;}
 function describe(node,...ids){node.setAttribute('aria-describedby',[...ids,...(node.target==='_blank'?['f-newtab']:[])].join(' '));return node;}
 function newTabNote(){const n=tr('span','newTab','f-sr-only');n.id='f-newtab';return n;}
 const KIND={news:'newsKind',recording:'recording',material:'material'},OPEN={news:'open',recording:'watchRecording',material:'openMaterial'};
 function contentCards(container,items,empty='noNews',heading='h3'){
  container.replaceChildren();if(!items.length){container.append(tr('p',empty,'f-muted f-empty'));return;}
  for(const item of items){
   const card=el('article','f-news-item'),meta=el('p','f-news-meta'),title=source(heading,item.title);
   meta.append(tr('span',KIND[item.kind]||'newsKind','f-chip'));
   if(item.createdAt&&Number.isFinite(Date.parse(item.createdAt)))meta.append(dateNode(limaDate(new Date(item.createdAt)),'span','short','f-news-date'));
   card.append(meta,title,source('p',item.body,'f-news-body'));
   if(item.url){const a=link(OPEN[item.kind]||'open',item.url,'f-text-link');if(item.id){title.id='f-c-'+item.id;describe(a,title.id);}card.append(a);}
   container.append(card);
  }
 }
 const findActivity=(event,id)=>[...event.activities,...(event.legacyActivities||[])].find(activity=>activity.id===id);
 // The heading level follows the host (h4 inside the saved summary's h3 section); the dashboard widget uses the short hint.
 function badges(container,attendance,event,{heading='h3',hint='badgesHint'}={}){container.replaceChildren();container.append(tr(heading,'badges'));if(!attendance.length)container.append(tr('p',hint,'f-muted'));else for(const record of attendance){const a=findActivity(event,record.activityId);if(a)container.append(source('p','✓ '+a.title,'f-badge'));}}
 // Scrolls a horizontal chip row just enough to show the item in full, clear of the right-edge fade (fiiu.css); only the row moves, never the page (the rows sit in sticky bars).
 function revealInRow(row,item){const box=item?.getBoundingClientRect?.(),frame=row?.getBoundingClientRect?.();if(!box||!frame)return;const shift=box.left<frame.left+8?box.left-frame.left-8:box.right>frame.right-36?box.right-frame.right+36:0;if(shift)row.scrollBy?.({left:shift});}
 window.Fiiu={rows,t,el,tr,button,link,source,field,check,api,status,dateNode,rangeNode,dateRange,limaDate,locale,refresh,contentCards,badges,findActivity,chronological,typeOf,countLabel,nextFor,hint,describe,newTabNote,revealInRow};
 window.nodalI18n?.onChange(refresh);refresh();
})();
